flink:
  app:
    parallelism:
      default: 50
      source: 100
      event: 100
      session: 700
      pre-agent-ip: 100
      agent-ip: 50
      agent: 50
      ip: 50
      guid: 100
      broadcast: 300
      metrics: 300

zookeeper:
  server: