flink:
  app:
    name: Sojourner Realtime Pipeline - LVS
    sink:
      dc: lvs
      kafka:
        topic:
          session:
            bot: behavior.totalv2.sojsession-bot-lvs
            non-bot: behavior.totalv2.sojsession-nonbot-lvs
          event:
            bot: behavior.totalv2.sojevent-bot-lvs
            non-bot: behavior.totalv2.sojevent-nonbot-lvs
            late: behavior.totalv2.sojevent-late-lvs
          signature:
            agent-ip: behavior.totalv2.signature.agent-ip-lvs
            agent: behavior.totalv2.signature.agent-lvs
            ip: behavior.totalv2.signature.ip-lvs
