flink:
  app:
    name: Sojourner Realtime Pipeline - QA
    parallelism:
      source: 2
      event: 2
      session: 2
      pre-agent-ip: 2
      agent-ip: 2
      agent: 2
      ip: 2
      broadcast: 2
      metrics: 2
    data-skew:
      is-filter: false
      guid-list:
        - abc
        - def
        - ghi
    source:
      from-timestamp: 0
      out-of-orderless-in-min: 3
      dc: lvs
    sink:
      dc: lvs
      kafka:
        topic:
          session:
            bot: behavior.trafficjam.sojsession.test
            non-bot: behavior.trafficjam.sojsession.test
          event:
            bot: behavior.trafficjam.custimized.3962
            non-bot: behavior.trafficjam.custimized.3962
          signature:
            agent-ip: behavior.trafficjam.agent.ip
            agent: behavior.trafficjam.agent
            ip: behavior.trafficjam.ip
        message-key:
          session: guid
          event: guid,pageId

kafka:
  consumer:
    group-id: sojourner-pathfinder-consumer-qa-local
    stream: behavior.trafficjam
    bootstrap-servers:
      lvs:
        - rhs-vvrvkiaa-kfk-lvs-1.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-vvrvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-vvrvkiaa-kfk-lvs-3.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-vvrvkiaa-kfk-lvs-4.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-vvrvkiaa-kfk-lvs-5.rheos-streaming-qa.svc.32.tess.io:9092

  producer:
    stream: behavior.trafficjam
    bootstrap-servers:
      lvs:
        - rhs-rurvkiaa-kfk-lvs-1.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-3.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-4.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-5.rheos-streaming-qa.svc.32.tess.io:9092

rheos:
  registry-url: https://rheos-services.qa.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: 6218c197-200e-49d7-b404-2a4dbf7595ef
      env: staging

zookeeper:
  enable: false
  server: rhs-tdtvkiaa-fzk-lvs-1.rheos-streaming-qa.svc.32.tess.io:2181,rhs-tdtvkiaa-fzk-lvs-2.rheos-streaming-qa.svc.32.tess.io:2181,rhs-tdtvkiaa-fzk-lvs-3.rheos-streaming-qa.svc.32.tess.io:2181,rhs-tdtvkiaa-fzk-lvs-4.rheos-streaming-qa.svc.32.tess.io:2181,rhs-tdtvkiaa-fzk-lvs-5.rheos-streaming-qa.svc.32.tess.io:2181

rest-client:
  base-url: https://sojubdportalservice.vip.qa.ebay.com

ua-parser-env: dev