flink:
  app:
    name: Sojourner Realtime Pipeline - totalnew
    sink:
      dc: rno
      kafka:
        topic:
          session:
            bot: behavior.total.new.sojsession.bot
            non-bot: behavior.total.new.sojsession.nonbot
          event:
            bot: behavior.total.new.sojevent.bot
            non-bot: behavior.total.new.sojevent.nonbot
            late: behavior.total.new.late-event
          signature:
            agent-ip: behavior.total.new.signature.agentIp
            agent: behavior.total.new.signature.agent
            ip: behavior.total.new.signature.ip

kafka:
  consumer:
    group-id: sojourner-pathfinder-realtime-test

  producer:
    stream: behavior.total.new
    bootstrap-servers:
      rno:
        - rhs-pbuvkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-pbuvkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-pbuvkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-pbuvkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-pbuvkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092