flink:
  app:
    name:
      full-pipeline: Sojourner LkpManager Test
    parallelism:
      source: 50
      event: 50
      pre-agent-ip: 50
      agent-ip: 50
      agent: 50
      ip: 50
      guid: 100
      broadcast: 200
      metrics: 200
