kafka:
  stream:
    behavior-pathfinder:
      group-id:
        default:
          rno: sojourner-pathfinder-rno-dq
          slc: sojourner-pathfinder-slc-dq
          lvs: sojourner-pathfinder-lvs-dq

    behavior-total-new:
      topic:
        dq:
          session: behavior.total.new.event.fordq
          cross-session: behavior.total.new.session.dq
      group-id:
        dq:
          session: sojourner-pathfinder-event-copy
          cross-session: sojourner-pathfinder-session-copy
flink:
  app:
    parallelism:
      source: 50

hdfs:
  path:
    intermediate-session: /cross_session