# case1
# rt pipeline normal case
# kafka source(pathfinder) -> flink cluster (rno) -> kafka sink (rno)

# case2
# sojourner-realtime-rno upgrade or system patch, we need switch rt pipeline to dr cluster(lvs)
# kafka source(pathfinder) -> flink cluster (lvs) -> kafka sink (rno)

kafka:
  consumer:
    stream: behavior.pathfinder
    topic:
      - behavior.pathfinder.events.total
    group-id:
      rno: sojourner-pathfinder-realtime
      lvs: sojourner-pathfinder-realtime
      slc: sojourner-pathfinder-realtime
    bootstrap-servers:
      rno:
        - rhs-glrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-glrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
      slc:
        - rhs-mwsvkiaa-kfk-slc-1.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-2.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-3.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-4.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-mwsvkiaa-kfk-slc-5.rheos-streaming-prod.svc.45.tess.io:9092
      lvs:
        - rhs-swsvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-swsvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

    max-poll-records: 5000
    # 50MB, default value is 50MB
    fetch-max-bytes: 52428800
    # 8MB, default value is 64KB
    receive-buffer: 8388608
    fetch-max-wait-ms: 100
    # 10MB, default value is 1MB
    max-partitions-fetch-bytes: 10485760
    auto-offset-reset: latest

  producer:
    producerId: sojourner
    stream: behavior.totalv2
    topic:
      session:
        bot: behavior.totalv2.sojsession-bot
        non-bot: behavior.totalv2.sojsession-nonbot
      event:
        bot: behavior.totalv2.sojevent-bot
        non-bot: behavior.totalv2.sojevent-nonbot
        late: behavior.totalv2.sojevent-late
      signature:
        agent-ip: behavior.totalv2.signature.agent-ip
        agent: behavior.totalv2.signature.agent
        ip: behavior.totalv2.signature.ip
    bootstrap-servers:
      - rhs-fxuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.37.tess.io:9092
      - rhs-fxuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.37.tess.io:9092
      - rhs-fxuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.37.tess.io:9092
      - rhs-fxuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.37.tess.io:9092
      - rhs-fxuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.37.tess.io:9092
    subject:
      event: behavior.pulsarv2.sojevent.schema
      session: behavior.pulsarv2.sojsession.schema

    batch-size: 524288
    acks: 1
    linger-ms: 50
    request-timeout-ms: 60000
    retries: 30
    buffer-memory: 268435456
    compression-type: lz4
    message-key:
      session: guid
      event:
        default: guid
        key1: guid
        key2: pageId
      signature:
        guid: guid
        ip: ip
        agent: userAgent
        agent-ip: userAgent

flink:
  app:
    name: Sojourner RT Pipeline
    parallelism:
      default: 50
      source: 100
      event: 100
      session: 600
      pre-agent-ip: 100
      agent-ip: 50
      agent: 50
      ip: 50
      guid: 100
      broadcast: 300
      metrics: 300
    slot-sharing-group:
      default: default
      source-event-lvs: lvs
      source-event-slc: slc
      source-event-rno: rno
      session: session
      pre-agent-ip: pre-agent-ip
      agent-ip: agent-ip
      agent: agent
      ip: ip
      guid: guid
      cross-session: cross-session
      broadcast: broadcast
    operator-name:
      source:
        rno: Pathfinder RNO Source
        lvs: Pathfinder LVS Source
        slc: Pathfinder SLC Source
    uid:
      source:
        rno: pathfinder-rno-source
        lvs: pathfinder-lvs-source
        slc: pathfinder-slc-source

    data-skew:
      is-filter: false
      guid-list:
        - abc
        - def
        - ghi
    checkpoint:
      data-dir: /opt/sojourner-ubd/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3
    hot-deploy: false

hdfs:
  path:
    parent: hdfs://apollo-rno/sys/soj/ubd/

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  schema-name:
    event:
    session:
    attribute:
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

zookeeper:
  enable: false
  sessionTimeoutMs: 15000
  connectionTimeoutMs: 5000
  maxRetries: 3
  baseSleepTimeMs: 1000
  namespace: sojourner

rest-client:
  rest-server: https://sojubdportalservice.vip.ebay.com
  auth-username: soj-flink-app
  auth-token: B65613BAE51443268AEBCAEF26C30ABE

ua-parser-env: prod