flink:
  app:
    name: Sojourner Realtime Pipeline - Prod
    parallelism:
      source: 200
      session: 1024
      broadcast: 512
      agent-ip: 150
    source:
      kafka:
        group-id: soj-realtime-prod-pathfinder-totalv3rno
        env: prod
        stream: behavior.pathfinder
        topic:
          - behavior.pathfinder.events.total
        start-offset: committed-offset
    sink:
      kafka:
        env: prod
        stream: behavior.totalv3
        dc: rno
        topic:
          event:
            bot: behavior.totalv3.sojevent-bot-rno
            non-bot: behavior.totalv3.sojevent-nonbot-rno
            late: behavior.totalv3.sojevent-late-rno
          session:
            bot: behavior.totalv3.sojsession-bot-rno
            non-bot: behavior.totalv3.sojsession-nonbot-rno
            metrics: behavior.totalv3.session.metrics-rno
          bot-signature:
            agent-ip: behavior.totalv3.signature.agent-ip-rno
            agent: behavior.totalv3.signature.agent-rno
            ip: behavior.totalv3.signature.ip-rno
