kafka:
  consumer:
    stream: behavior.totalv2
    topic: behavior.totalv2.session.fordq
    group-id: sojourner-pathfinder-full-session-dq
    bootstrap-servers:
      rno:
        - rhs-fxuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.37.tess.io:9092

flink:
  app:
    parallelism:
      source: 100
      pre-agent-ip: 300
      agent: 50
      agent-ip: 50
      ip: 50
      guid: 50
      broadcast: 100
      metrics: 500


hdfs:
  path:
    intermediate-session: /cross_session_full_pipeline
    signatures: /signatures_test_full_pipeline