flink:
  app:
    name: Sojourner Realtime Pipeline Pre-Prod - SINK TO HDFS Apollo
    parallelism:
      source: 200
      session: 1024
      broadcast: 512
      agent-ip: 150
    source:
      kafka:
        group-id: sojourner-realtime-hdfs-pre-prod
        env: prod
        stream: behavior.pathfinder
        topic:
          - behavior.pathfinder.events.total
        start-offset: latest
    sink:
      hdfs:
        session:
          base-path: hdfs://apollo-router/sys/soj/ubd/sessions/
          watermark-path: hdfs://apollo-router/sys/soj/ubd/watermark/sessions/
        event:
          base-path: hdfs://apollo-router/sys/soj/ubd/events/
          watermark-path: hdfs://apollo-router/sys/soj/ubd/watermark/events/
    metric:
      session:
        watermark-delay: sojourner-session-watermark-delay-time
      event:
        watermark-delay: sojourner-event-watermark-delay-time
