flink:
  app:
    checkpoint:
      data-dir: /tmp/flink/checkpoints/sojourner-realtime/
      # 10 mins
      interval-ms: 600000
      # 15 mins
      timeout-ms: 900000
    watermark:
      max-out-of-orderness-in-min: 3
      idle-source-timeout-in-min: 10
    filter:
      large-message:
        max-bytes: 819200
        sub-url-query-string-length: 4096
        truncate-url-query-string: true
    sink:
      kafka:
        subject:
          event: behavior.sojourner.sojevent.schema
          session: behavior.sojourner.sojsession.schema
          session-metrics: behavior.sojourner.session.metrics.schema

kafka:
  consumer:
    # 5000, default value is 500
    max-poll-records: 5000
    # 50MB, default value is 50MB
    fetch-max-bytes: 52428800
    # 4MB, default value is 64KB
    receive-buffer: 4194304
    # 25MB, default value is 1MB
    max-partitions-fetch-bytes: 26214400
    # when offset cannot be found, read from earliest
    auto-offset-reset: earliest

  producer:
    # 1MB, default value is 16KB
    batch-size: 1048576
    # 50ms, default value is 0
    linger-ms: 50
    # 30s, default value is 30s
    request-timeout-ms: 30000
    # 2147483647, default value is 2147483647(Integer.MAX_VALUE)
    retries: 2147483647
    # 256MB, default value is 32MB
    buffer-memory: 268435456
    # default value is none
    compression-type: lz4
    # 3m, default value is 120s
    delivery-timeout-ms: 180000
    # 1000000 bytes, default value is 1MB
    max-request-size: 1000000

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    auth-type: IAF
    iaf:
      id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

ua-parser-env: prod

agent-whitelist:
  - GingerClient/0.11.2-RELEASE
