kafka:
  consumer:
    group-id: sojourner-pathfinder-consumer-test-11

flink:
  app:
    name: Sojourner RT Pipeline
    parallelism:
      default: 7
      source: 7
      event: 7
      session: 7
      pre-agent-ip: 7
      agent-ip: 7
      agent: 7
      ip: 7
      guid: 7
      broadcast: 7
      metrics: 7