flink:
  app:
    name: Sojourner Realtime Pipeline - Dev
    parallelism:
      default: 1
      source: 1
      event: 1
      session: 1
      pre-agent-ip: 1
      agent-ip: 1
      agent: 1
      ip: 1
      broadcast: 1
      metrics: 1
    metric:
      window-size: 10
    data-skew:
      is-filter: false
      guid-list:
        - abc
        - def
        - ghi
    source:
      from-timestamp: 0
      out-of-orderless-in-min: 3
      dc: slc
    sink:
      dc: slc
      kafka:
        topic:
          session:
            bot: behavior.totalv2.sojsession-bot
            non-bot: behavior.totalv2.sojsession-nonbot
          event:
            bot: behavior.totalv2.sojevent-bot
            non-bot: behavior.totalv2.sojevent-nonbot
            late: behavior.totalv2.sojevent-late
          signature:
            agent-ip: behavior.totalv2.signature.agent-ip
            agent: behavior.totalv2.signature.agent
            ip: behavior.totalv2.signature.ip

kafka:
  consumer:
    group-id: sojourner-pathfinder-realtime-local
    stream: behavior.pathfinder
    bootstrap-servers:
      slc:
        - rhs-jhnaniaa-kfk-1.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-jhnaniaa-kfk-2.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-jhnaniaa-kfk-3.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-jhnaniaa-kfk-4.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-jhnaniaa-kfk-5.rheos-streaming-qa.stratus.qa.ebay.com:9092

    max-poll-records: 500
    # 50MB, default value is 50MB
    fetch-max-bytes: 52428800
    # 128KB, default value is 64KB
    receive-buffer: 131072
    fetch-max-wait-ms: 100
    # 1MB, default value is 1MB
    max-partitions-fetch-bytes: 1048576
    auto-offset-reset: latest


  producer:
    stream: behavior.totalv2
    bootstrap-servers:
      slc:
        - localhost:9092
    auth-enabled: false

    # 16KB
    batch-size: 16384
    acks: 1
    linger-ms: 10
    # 30s
    request-timeout-ms: 30000
    retries: 30
    # 32MB
    buffer-memory: 33554432
    compression-type: lz4
    # 2min
    delivery-timeout-ms: 120000

rheos:
  registry-url: https://rheos-services.qa.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: 6218c197-200e-49d7-b404-2a4dbf7595ef
      env: staging

zookeeper:
  enable: false
  server: rhs-tdtvkiaa-fzk-lvs-1.rheos-streaming-qa.svc.32.tess.io:2181,rhs-tdtvkiaa-fzk-lvs-2.rheos-streaming-qa.svc.32.tess.io:2181,rhs-tdtvkiaa-fzk-lvs-3.rheos-streaming-qa.svc.32.tess.io:2181,rhs-tdtvkiaa-fzk-lvs-4.rheos-streaming-qa.svc.32.tess.io:2181,rhs-tdtvkiaa-fzk-lvs-5.rheos-streaming-qa.svc.32.tess.io:2181

rest-client:
  base-url: https://sojsvc.vip.qa.ebay.com

ua-parser-env: dev