flink:
  app:
    name: Sojourner Realtime Pipeline - Pre-Prod
    parallelism:
      source: 200
      session: 1200
      broadcast: 600
      agent-ip: 150
    source:
      kafka:
        group-id: sojourner-realtime-pre-prod
        env: prod
        stream: behavior.pathfinder
        topic:
          - behavior.pathfinder.events.total
        from-timestamp: latest
    sink:
      kafka:
        env: prod
        stream: behavior.total.new
        dc: rno
        topic:
          event:
            bot: behavior.total.new.sojevent.bot
            non-bot: behavior.total.new.sojevent.nonbot
            late: behavior.total.new.sojevent-late
          session:
            bot: behavior.total.new.sojsession.bot
            non-bot: behavior.total.new.sojsession.nonbot
            metrics: behavior.total.new.session.metrics
          bot-signature:
            agent-ip: behavior.totalv3.signature.agent-ip-rno
            agent: behavior.totalv3.signature.agent-rno
            ip: behavior.totalv3.signature.ip-rno
