flink:
  app:
    name: Sojourner Realtime Pipeline - RNO
    sink:
      dc: rno
      kafka:
        topic:
          session:
            bot: behavior.totalv2.sojsession-bot-rno
            non-bot: behavior.totalv2.sojsession-nonbot-rno
          event:
            bot: behavior.totalv2.sojevent-bot-rno
            non-bot: behavior.totalv2.sojevent-nonbot-rno
            late: behavior.totalv2.sojevent-late-rno
          signature:
            agent-ip: behavior.totalv2.signature.agent-ip-rno
            agent: behavior.totalv2.signature.agent-rno
            ip: behavior.totalv2.signature.ip-rno
