flink:
  app:
    name: Sojourner Realtime Pipeline - Staging
    parallelism:
      source: 2
      session: 2
      agent-ip: 2
      sink: 2
    watermark:
      out-of-orderless-in-min: 3
    source:
      kafka:
        group-id: sojourner-realtime-staging
        env: stage
        stream: behavior.pathfinder
        dc: slc
        topic:
          - behavior.pathfinder.events.total
        from-timestamp: latest
    sink:
      kafka:
        env: stage
        stream: behavior.totalv2
        dc: slc
        topic:
          event:
            bot: behavior.totalv2.sojevent-bot
            non-bot: behavior.totalv2.sojevent-nonbot
          session:
            bot: behavior.totalv2.sojsession-bot
            non-bot: behavior.totalv2.sojsession-nonbot
        subject:
          event: behavior.sojourner.sojevent.schema
          session: behavior.sojourner.sojsession.schema

rheos:
  registry-url: https://rheos-services.qa.ebay.com
  client:
    auth-type: IAF
    iaf:
      id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
      secret: 6218c197-200e-49d7-b404-2a4dbf7595ef
      env: staging

ua-parser-env: dev