flink:
  app:
    checkpoint:
      data-dir: /tmp/flink/checkpoints/sojourner-realtime/
      # 10 mins
      interval-ms: 600000
      # 15 mins
      timeout-ms: 900000
    watermark:
      max-out-of-orderness-in-min: 3
      idle-source-timeout-in-min: 10
    filter:
      large-message:
        max-bytes: 819200
        sub-url-query-string-length: 4096
        truncate-url-query-string: true
    sink:
      kafka:
        subject:
          event: behavior.sojourner.sojevent.schema
          session: behavior.sojourner.sojsession.schema

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    auth-type: IAF
    iaf:
      id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

ua-parser-env: prod

agent-whitelist:
  - GingerClient/0.11.2-RELEASE
