kafka:
  consumer:
    topic: behavior.total.new.signature.agent
    group-id: sojourner-pathfinder-agent

flink:
  app:
    name: Sojourner Agent Signature HDFS Load Pipeline
    parallelism:
      source: 10
      sink:
        hdfs: 10

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/signatures/type=agent
    class-name: com.ebay.sojourner.common.model.BotSignature