kafka:
  common:
    consumer:
      brokers:
        bot: rhs-okrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092,rhs-okrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092,rhs-okrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092,rhs-okrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092,rhs-okrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
        non-bot: rhs-okrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092,rhs-okrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092,rhs-okrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092,rhs-okrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092,rhs-okrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
      topic:
        bot: behavior.pulsar.sojsession.botsession
        non-bot: behavior.pulsar.sojsession.sessionend
      group-id:
        bot: sojourner-jetstream-session-bot
        non-bot: sojourner-jetstream-session-non-bot

flink:
  app:
    parallelism:
      source:
        bot: 20
        non-bot: 15
      sink:
        hdfs: 50

rheos:
  serviceUrl: https://rheos-services.stratus.ebay.com
  iaf:
    secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
    env: production

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/jetstrem_sessions
    class-name: com.ebay.sojourner.common.model.JetStreamOutputSession