kafka:
  consumer:
    #    topic: behavior.total.new.signature.agentIp
    #    group-id: sojourner-pathfinder-agent-ip
    topic: behavior.totalv2.signature.agent-ip
    group-id: sojourner-total-dumper-lvs

flink:
  app:
    name: Sojourner AgentIp Signature HDFS Load Pipeline
    parallelism:
      source: 10
      sink:
        hdfs: 10

hdfs:
  dump:
    path: hdfs://hercules/sys/soj/ubd/signatures/type=agentIp
    class-name: com.ebay.sojourner.common.model.BotSignature