kafka:
  consumer:
    stream: behavior.pulsar
    topic: behavior.pulsar.sojsession.botsession
    group-id: sojourner-jetstream-session-bot
    bootstrap-servers:
      rno:
        - rhs-okrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092

flink:
  app:
    name:
      hdfs-dump: Jetstream Bot Session HDFS Load Pipeline
    parallelism:
      source: 20
      sink:
        hdfs: 20

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/jetstream_sessions/type=bot/
    class-name: com.ebay.sojourner.common.model.JetStreamOutputSession