kafka:
  consumer:
    topic: behavior.total.new.sojsession.bot
    group-id: sojourner-pathfinder-session-bot

flink:
  app:
    name: Sojourner Bot Session HDFS Load Pipeline
    parallelism:
      source: 20
      sink:
        hdfs: 20

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/sessions/type=bot
    class-name: com.ebay.sojourner.common.model.SojSession