kafka:
  consumer:
    topic: behavior.total.new.sojsession
    group-id: sojourner-pathfinder-session

flink:
  app:
    name:
      hdfs-dump: Sojourner Session HDFS Load Pipeline
    parallelism:
      source:
        default: 50
      sink:
        hdfs: 50

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/sessions
    class-name: com.ebay.sojourner.common.model.SojSession