kafka:
  common:
    consumer:
      max-poll-records: 3000
      receive-buffer: 8388608
      fetch-max-bytes: 262144000
      fetch-max-wait-ms: 1000
      max-partitions-fetch-bytes: 8388608
      auto-offset-reset: latest
      brokers:
        default: rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092,rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092,rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092,rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092,rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092
      topic:
        default: behavior.total.new.sojevent
      group-id:
        default: sojourner-pathfinder-event

    producer:
      batch-size: 4096
      request-timeout-ms: 60000
      brokers:
        default: rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092,rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092,rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092,rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092,rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092
      topic:
        default: behavior.total.new.sojevent
      message-key:
        session: guid
        event: guid

flink:
  app:
    name:
      hdfs-dump: Sojourner HDFS Load Pipeline
      kafka-dump: Sojourner Kafka Load Pipeline
    parallelism:
      source:
        default: 150
      sink:
        kafka: 100
        hdfs: 150
    checkpoint:
      data-dir: /opt/sojourner-ubd/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1

rheos:
  serviceUrl: https://rheos-services.stratus.ebay.com
  iaf:
    secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
    env: production

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/events
    class-name: com.ebay.sojourner.common.model.SojEvent

zookeeper:
  server:
    - zk-0.sojzk-ns.svc.32.tess.io:2181
    - zk-1.sojzk-ns.svc.32.tess.io:2181
    - zk-2.sojzk-ns.svc.32.tess.io:2181
  sessionTimeoutMs: 15000
  connectionTimeoutMs: 5000
  maxRetries: 3
  baseSleepTimeMs: 1000
  namespace: sojourner
  nodepath: /rule/publish/notification

rest-client:
  rest-server: https://sojubdportalservice.vip.ebay.com
  published-rule-list: /api/rule/list/published
  specified-rule: /api/rule/
  auth-username-key: X-Auth-Username
  auth-username-value: soj-flink-app
  auth-token-key: X-Auth-Token
  anth-token-value: B65613BAE51443268AEBCAEF26C30ABE