kafka:
  consumer:
    topic: behavior.totalv2.sojsession-nonbot

flink:
  app:
    name: Sojourner Non Bot Session HDFS Load Pipeline
    parallelism:
      source: 15
      sink:
        hdfs: 15

hdfs:
  dump:
    path:
      same-day: hdfs://apollo-rno/sys/soj/ubd/sessions/category=sameday/type=nonbot
      cross-day: hdfs://apollo-rno/sys/soj/ubd/sessions/category=crossday/type=nonbot
    watermark-path: hdfs://apollo-rno/sys/soj/ubd/watermark/sessions/type=nonbot