kafka:
  consumer:
    topic: behavior.totalv2.signature.guid
    group-id: sojourner-pathfinder-guid

flink:
  app:
    name:
      hdfs-dump: Sojourner Guid Signature HDFS Load Pipeline
    parallelism:
      source: 20
      sink:
        hdfs: 20

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/signatures/type=guid
    class-name: com.ebay.sojourner.common.model.BotSignature