kafka:
  consumer:
    topic: behavior.totalv2.signature.agentIp
    group-id: sojourner-pathfinder-agent-ip

flink:
  app:
    name: Sojourner AgentIp Signature HDFS Load Pipeline
    parallelism:
      source: 20
      sink:
        hdfs: 20

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/signatures/type=agentIp
    class-name: com.ebay.sojourner.common.model.BotSignature