kafka:
  consumer:
    topic: behavior.total.new.signature.ip
    group-id: sojourner-pathfinder-ip

flink:
  app:
    name:
      hdfs-dump: Sojourner Ip Signature HDFS Load Pipeline
    parallelism:
      source: 10
      sink:
        hdfs: 10

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/signatures/type=ip
    class-name: com.ebay.sojourner.common.model.BotSignature