kafka:
  common:
    consumer:
      brokers:
        bot: rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092,rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092,rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092,rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092,rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092
        non-bot: rhs-okrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092,rhs-okrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092,rhs-okrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092,rhs-okrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092,rhs-okrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
      topic:
        bot: behavior.pulsar.misc.bot
        non-bot: behavior.total.sojevent.total
      group-id:
        bot: sojourner-jetstream-event-bot
        non-bot: sojourner-jetstream-event-non-bot

flink:
  app:
    parallelism:
      source:
        bot: 30
        non-bot: 150
      sink:
        hdfs: 300

rheos:
  serviceUrl: https://rheos-services.stratus.ebay.com
  iaf:
    secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
    env: production

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/jetstrem_events
    class-name: com.ebay.sojourner.common.model.JetStreamOutputEvent