kafka:
  consumer:
    stream: behavior.total.new
    topic: behavior.total.new.pulsarevent
    group-id: sojourner-jetstream-pulsar-event-dump

flink:
  app:
    name: Jetstream Pulsar Event HDFS Load Pipeline
    parallelism:
      source: 50
      sink:
        hdfs: 50

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/pulsar_event/
    class-name: com.ebay.sojourner.common.model.PulsarEvents