kafka:
  consumer:
    stream: behavior.total.new
    topic: behavior.total.new.sojevent
    group-id: sojourner-pathfinder-event-non-bot
    bootstrap-servers:
      rno:
        - rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092

  common:
    consumer:
      max-poll-records: 3000
      receive-buffer: 8388608
      fetch-max-bytes: 262144000
      fetch-max-wait-ms: 1000
      max-partitions-fetch-bytes: 8388608
      auto-offset-reset: latest
    producer:
      batch-size: 100000
      linger.ms: 5
      request-timeout-ms: 60000
      retries: 3
      message-key:
        session: guid
        event: guid

  producer:
    stream:
    topic:
    bootstrap-servers:
      rno:

flink:
  app:
    name:
      hdfs-dump: Sojourner Non Bot Event HDFS Load Pipeline
      kafka-dump: Sojourner Kafka Load Pipeline
    parallelism:
      source: 150
      sink:
        kafka: 100
        hdfs: 150
    checkpoint:
      data-dir: /opt/sojourner-ubd/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/events/type=nonbot
    class-name: com.ebay.sojourner.common.model.SojEvent

zookeeper:
  sessionTimeoutMs: 15000
  connectionTimeoutMs: 5000
  maxRetries: 3
  baseSleepTimeMs: 1000
  namespace: sojourner

rest-client:
  rest-server: https://sojubdportalservice.vip.ebay.com
  auth-username: soj-flink-app
  anth-token: B65613BAE51443268AEBCAEF26C30ABE