kafka:
  consumer:
    stream: behavior.total
    topic: behavior.total.sojevent.total
    group-id: sojourner-jetstream-event-non-bot
    bootstrap-servers:
      rno:
        - rhs-rdrvkiaa-kfk-rno-11.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-rdrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-rdrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-rdrvkiaa-kfk-rno-31.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-rdrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092

flink:
  app:
    name:
      hdfs-dump: Jetstream Non Bot Event HDFS Load Pipeline
    parallelism:
      source:
        default: 150
      sink:
        hdfs: 150

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/jetstream_events/type=nonbot/
    class-name: com.ebay.sojourner.common.model.JetStreamOutputEvent