kafka:
  consumer:
    stream: behavior.pulsarv2.test
    topic:
      - behavior.pulsarv2.test.buyer.risk
    group-id: sojourner-customized-data-quality-check
    bootstrap-servers:
      slc:
        - rhs-kxwvkiaa-kfk-slc-1.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-2.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-3.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-4.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-5.rheos-streaming-prod.svc.45.tess.io:9092

    max-poll-records: 5000
    # 50MB, default value is 50MB
    fetch-max-bytes: 52428800
    # 8MB, default value is 64KB
    receive-buffer: 8388608
    fetch-max-wait-ms: 100
    # 10MB, default value is 1MB
    max-partitions-fetch-bytes: 10485760
    auto-offset-reset: latest
    # 60s, default is disabled
    partition-discovery-interval-ms: 60000

flink:
  app:
    name: Sojourner Customized Buyer Risk Topic Event HDFS Load Pipeline
    parallelism:
      source: 40
      sink:
        hdfs: 40
    operator-name:
      source: Sojourner Customized Buyer Risk Topic Event Source
      sink: Sojourner Customized Buyer Risk Topic Event Sink
    uid:
      source: sojourner-customized-buyer-risk-topic-event-source
      sink: sojourner-customized-buyer-risk-topic-event-sink
    source:
      dc: slc
    sink:
      hdfs:
        path: hdfs://apollo-rno/sys/soj/ubd/customized-topic-dq-check/topic=risk/
