kafkaConsumerConfig:
  bootstrapServersForRNO:
    - rhs-glrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-glrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-glrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-glrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-glrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
  bootstrapServersForSLC:
    - rhs-mwsvkiaa-kfk-slc-1.rheos-streaming-prod.svc.45.tess.io:9092
    - rhs-mwsvkiaa-kfk-slc-2.rheos-streaming-prod.svc.45.tess.io:9092
    - rhs-mwsvkiaa-kfk-slc-3.rheos-streaming-prod.svc.45.tess.io:9092
    - rhs-mwsvkiaa-kfk-slc-4.rheos-streaming-prod.svc.45.tess.io:9092
    - rhs-mwsvkiaa-kfk-slc-5.rheos-streaming-prod.svc.45.tess.io:9092
  bootstrapServersForLVS:
    - rhs-swsvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
    - rhs-swsvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
    - rhs-swsvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
    - rhs-swsvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
    - rhs-swsvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092
  bootstrapServersForQA:
    - rhs-vvrvkiaa-kfk-lvs-1.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-vvrvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-vvrvkiaa-kfk-lvs-3.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-vvrvkiaa-kfk-lvs-4.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-vvrvkiaa-kfk-lvs-5.rheos-streaming-qa.svc.32.tess.io:9092
  bootstrapServersForJetStreamSession:
    - rhs-okrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
  bootstrapServersForJetStreamEvent:
    - rhs-okrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
  groupIdForLVS: sojourner-pathfinder-lvs
  groupIdForSLC: sojourner-pathfinder-slc
  groupIdForRNO: sojourner-pathfinder-rno
  groupIdForLVSDQ: sojourner-pathfinder-lvs-dq
  groupIdForSLCDQ: sojourner-pathfinder-slc-dq
  groupIdForRNODQ: sojourner-pathfinder-rno-dq
  groupIdForQA: sojourner-pathfinder-qa
  groupIdForSession: sojourner-pathfinder-session
  groupIdForEvent: sojourner-pathfinder-event
  groupIdForBot: sojourner-pathfinder-bot
  groupIdForCopy: sojourner-pathfinder-copy
  groupIdForCrossSession: sojourner-pathfinder-cross-session-dq
  groupIdForJetStreamNonBotSession: jetstream-non-bot-session
  groupIdForJetStreamNonBotEvent: jetstream-non-bot-event
  groupIdForJetStreamBotSession: jetstream-bot-session
  groupIdForJetStreamBotEvent: jetstream-bot-event
  topic: behavior.pathfinder.events.total
  jetStreamNonBotSessionTopic: behavior.pulsar.sojsession.sessionend
  jetStreamNonBotEventTopic: behavior.total.sojevent.total
  jetStreamBotSessionTopic: behavior.pulsar.sojsession.botsession
  jetStreamBotEventTopic: behavior.pulsar.misc.bot

kafkaProducerConfig:
  bootstrapServersForSession:
    - rhs-rurvkiaa-kfk-lvs-1.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-3.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-4.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-5.rheos-streaming-qa.svc.32.tess.io:9092
  bootstrapServersForEvent:
    - rhs-rurvkiaa-kfk-lvs-1.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-3.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-4.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-5.rheos-streaming-qa.svc.32.tess.io:9092
  bootstrapServersForBot:
    - rhs-rurvkiaa-kfk-lvs-1.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-3.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-4.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-5.rheos-streaming-qa.svc.32.tess.io:9092
  bootstrapServersForCopy:
    - rhs-rurvkiaa-kfk-lvs-1.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-3.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-4.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-5.rheos-streaming-qa.svc.32.tess.io:9092
  bootstrapServersForCrossSessionDQ:
    - rhs-rurvkiaa-kfk-lvs-1.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-3.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-4.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-rurvkiaa-kfk-lvs-5.rheos-streaming-qa.svc.32.tess.io:9092
  sessionTopic: behavior.trafficjam.session
  eventTopic: behavior.trafficjam.event
  botTopic: behavior.trafficjam.bot
  copyTopic: behavior.trafficjam.pathfinder.copy
  crossSessionDQTopic: behavior.trafficjam.session.dq

rheos:
  serviceUrl: https://rheos-services.qa.ebay.com
  iaf:
    secret: 6218c197-200e-49d7-b404-2a4dbf7595ef
    env: staging

flink:
  app:
    nameForFullPipeline: Unified Bot Detection RT Pipeline
    nameForRTLoadPipeline: Unified Bot Detection RT Load Pipeline
    nameForDQPipeline: Unified Bot Detection RT DQ Pipeline
    nameForHotDeployPipeline: Unified Bot Detection RT Hot Deploy Pipeline
    nameForKafkaSinkPipeline: Unified Bot Detection RT kafka Sink Pipeline
    nameForKafkaCopyPipeline: Unified Bot Detection RT kafka Copy Pipeline
    source-parallelism: 2
    event-parallelism: 2
    session-parallelism: 2
    pre-agentIp-parallelism: 2
    agentIp-parallelism: 2
    agent-parallelism: 2
    ip-parallelism: 2
    guid-parallelism: 2
    copy-kafka-parallelism: 2
    event-kafka-parallelism: 2
    session-kafka-parallelism: 2
    cross-session-kafka-parallelism: 2
    bot-kafka-parallelism: 2
    broadcast-parallelism: 2
    metrics-parallelism: 2
  checkpoint:
    data-dir: /opt/sojourner-ubd/checkpoint
    interval: 5m
    timeout: 15m
    min-pause-between: 2m
    max-concurrent: 1

hdfs:
  sinkParentPath: hdfs://hadoop-qa-5878.lvs02.dev.ebayc3.com:8020/user/o_ubi/soj/ubd
  sinkEventPath: /events
  sinkSessionPath: /sessions
  sinkSignaturePath: /signatures
  sinkLateEventPath: /late_events
  sinkJetstreamEventPath: /jetstream_events
  sinkJetstreamSessionPath: /jetstream_sessions