kafka:
  bootstrapServers:
    - rhs-okrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
  groupId: sojourner-newsource
  topic: behavior.pulsar.misc.bot

rheos:
  serviceUrl: https://rheos-services.stratus.ebay.com
  iaf:
    secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
    env: production

flink:
  app:
    name: Unified Bot Detection RT Pipeline
    source-parallelism: 30
  checkpoint:
    data-dir: /opt/sojourner-ubd/checkpoint
    interval: 5m
    timeout: 15m
    min-pause-between: 2m
    max-concurrent: 1