kafkaConsumerConfig:
  bootstrapServersForRNO:
    - rhs-glrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-glrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-glrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-glrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-glrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
  bootstrapServersForSLC:
    - rhs-mwsvkiaa-kfk-slc-1.rheos-streaming-prod.svc.45.tess.io:9092
    - rhs-mwsvkiaa-kfk-slc-2.rheos-streaming-prod.svc.45.tess.io:9092
    - rhs-mwsvkiaa-kfk-slc-3.rheos-streaming-prod.svc.45.tess.io:9092
    - rhs-mwsvkiaa-kfk-slc-4.rheos-streaming-prod.svc.45.tess.io:9092
    - rhs-mwsvkiaa-kfk-slc-5.rheos-streaming-prod.svc.45.tess.io:9092
  bootstrapServersForLVS:
    - rhs-swsvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
    - rhs-swsvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
    - rhs-swsvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
    - rhs-swsvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
    - rhs-swsvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092
  bootstrapServersForQA:
    - rhs-vvrvkiaa-kfk-lvs-1.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-vvrvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-vvrvkiaa-kfk-lvs-3.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-vvrvkiaa-kfk-lvs-4.rheos-streaming-qa.svc.32.tess.io:9092
    - rhs-vvrvkiaa-kfk-lvs-5.rheos-streaming-qa.svc.32.tess.io:9092
  groupIdForLVS: sojourner-pathfinder-lvs-test
  groupIdForSLC: sojourner-pathfinder-slc-test
  groupIdForRNO: sojourner-pathfinder-rno-test
  groupIdForLVSDQ: sojourner-pathfinder-lvs-dq
  groupIdForSLCDQ: sojourner-pathfinder-slc-dq
  groupIdForRNODQ: sojourner-pathfinder-rno-dq
  groupIdForQA: sojourner-pathfinder-qa
  groupIdForSession: sojourner-pathfinder-session
  groupIdForEvent: sojourner-pathfinder-event
  groupIdForBot: sojourner-pathfinder-bot
  groupIdForCopy: sojourner-pathfinder-copy
  topic: behavior.pathfinder.events.total

kafkaProducerConfig:
  bootstrapServersForSession:
    - rhs-rdrvkiaa-kfk-rno-31.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-11.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
  bootstrapServersForEvent:
    - rhs-rdrvkiaa-kfk-rno-31.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-11.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
  bootstrapServersForBot:
    - rhs-rdrvkiaa-kfk-rno-31.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-11.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
  bootstrapServersForCopy:
    - rhs-rdrvkiaa-kfk-rno-31.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-11.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
    - rhs-rdrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
  sessionTopic: behavior.trafficjam.session
  eventTopic: behavior.trafficjam.event
  botTopic: behavior.trafficjam.bot
  copyTopic: behavior.trafficjam.pathfinder.copy

rheos:
  serviceUrl: https://rheos-services.stratus.ebay.com
  iaf:
    secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
    env: production

flink:
  app:
    nameForFullPipeline: Unified Bot Detection RT Pipeline
    nameForRTLoadPipeline: Unified Bot Detection RT Load Pipeline
    nameForDQPipeline: Unified Bot Detection RT DQ Pipeline
    nameForHotDeployPipeline: Unified Bot Detection RT Hot Deploy Pipeline
    nameForKafkaSinkPipeline: Unified Bot Detection RT kafka Sink Pipeline
    nameForKafkaCopyPipeline: Unified Bot Detection RT kafka Copy Pipeline
    source-parallelism: 100
    event-parallelism: 120
    session-parallelism: 120
    pre-agentIp-parallelism: 350
    agentIp-parallelism: 300
    agent-parallelism: 300
    ip-parallelism: 300
    guid-parallelism: 350
    copy-kafka-parallelism: 50
    event-kafka-parallelism: 50
    session-kafka-parallelism: 50
    bot-kafka-parallelism: 50
    broadcast-parallelism: 350
    metrics-parallelism: 120
  checkpoint:
    data-dir: /opt/sojourner-ubd/checkpoint
    interval: 5m
    timeout: 15m
    min-pause-between: 2m
    max-concurrent: 1

hdfs:
  sinkParentPath: hdfs://apollo-rno/sys/soj/ubd
  sinkEventPath: /events
  sinkSessionPath: /sessions
  sinkSignaturePath: /signatures
  sinkLateEventPath: /late_events