kafka:
  bootstrapServersForRNO:
    - rhs-glrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-glrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-glrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-glrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-glrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
  bootstrapServersForSLC:
    - rhs-pathfinder-kfk-1.stratus.slc.ebay.com:9092
    - rhs-pathfinder-kfk-2.stratus.slc.ebay.com:9092
    - rhs-pathfinder-kfk-3.stratus.slc.ebay.com:9092
    - rhs-pathfinder-kfk-4.stratus.slc.ebay.com:9092
    - rhs-pathfinder-kfk-5.stratus.slc.ebay.com:9092
  bootstrapServersForLVS:
    - rhs-pathfinder-kfk-2.stratus.lvs.ebay.com:9092
    - rhs-pathfinder-kfk-3.stratus.lvs.ebay.com:9092
    - rhs-pathfinder-kfk-4.stratus.lvs.ebay.com:9092
    - rhs-pathfinder-kfk-5.stratus.lvs.ebay.com:9092
    - rhs-pathfinder-kfk-6.stratus.lvs.ebay.com:9092
  bootstrapServersForSOJ:
    - rhs-okrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
    - rhs-okrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
  groupId: sojourner-pathfinder
  topic: behavior.pathfinder.events.total

rheos:
  serviceUrl: https://rheos-services.stratus.ebay.com
  iaf:
    secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
    env: production

flink:
  app:
    name: Unified Bot Detection RT Pipeline
    source-parallelism: 100
    event-parallelism: 150
  checkpoint:
    data-dir: /opt/sojourner-ubd/checkpoint
    interval: 5m
    timeout: 15m
    min-pause-between: 2m
    max-concurrent: 1