kafka:
  consumer:
    data-center: RNO
    topic:
      - behavior.totalv2.sojsession-nonbot
    group-id:
      lvs: sojourner-total-dumper-lvs

flink:
  app:
    name: Sojourner LVS Non Bot Session HDFS Load Pipeline
    parallelism:
      source: 15
      sink:
        hdfs: 15
    metric:
      watermark-process-progress: sojourner-ubd-nonbot-session-watermark-delay-time

hdfs:
  dump:
    path:
      open: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=open/type=nonbot
      same-day: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=sameday/type=nonbot
      cross-day: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=crossday/type=nonbot
    watermark-path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/ubi_session_watermark_lkp/type=nonbot