kafka:
  consumer:
    data-center: LVS
    topic:
      - behavior.totalv2.signature.agent
    group-id:
      lvs: sojourner-total-dumper-rno
    bootstrap-servers:
      lvs:
        - rhs-ravvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

flink:
  app:
    name: Sojourner RNO Agent Signature HDFS Load Pipeline
    parallelism:
      source: 10
      sink:
        hdfs: 10
    operator-name:
      source: Sojourner Total RNO Signature Agent Source
      sink: Sojourner Total RNO Signature Agent Sink
    uid:
      source: sojourner-total-rno-signature-agent-source
      sink: sojourner-total-rno-signature-agent-sink

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/signatures/type=agent
    class-name: com.ebay.sojourner.common.model.BotSignature