kafka:
  consumer:
    stream: behavior.totalv3
    topic:
      - behavior.totalv3.sojevent-nonbot-lvs
      - behavior.totalv3.sojevent-nonbot-rno
    group-id: sojourner-total-dumper-rno
    bootstrap-servers:
      rno:
        - rhs-lpdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      lvs:
        - rhs-opdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092

flink:
  app:
    name: Sojourner RNO Non Bot Event HDFS Load Pipeline
    parallelism:
      source: 400
      sink:
        hdfs: 500
    operator-name:
      source: Sojourner Total RNO Nonbot Event Source
      pass-through: RNO Byte To Nonbot Event
      assgin-watermark: RNO Nonbot Event Watermark Assign
      extract-watermark: RNO Nonbot Event Timestamp Extract
      sink:
        event: Sojourner Total RNO Nonbot Event Sink
        watermark: Sojourner Total RNO Nonbot Event Watermark Sink
    uid:
      source: sojourner-total-rno-nonbot-event-source
      pass-through: rno-byte-to-nonbot-event
      assgin-watermark: rno-nonbot-event-watermak-assign
      extract-watermark: rno-nonbot-event-timestamp-extract
      sink:
        event: sojourner-total-rno-nonbot-event-sink
        watermark: sojourner-total-rno-nonbot-event-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-nonbot-event-watermark-delay-time
    source:
      dc: lvs
    sink:
      hdfs:
        path: hdfs://apollo-router/sys/edw/working/ubi/ubi_w/soj/stg_ubi_event_dump_w/type=nonbot
        watermark-path: hdfs://apollo-router/sys/edw/working/ubi/ubi_w/soj/ubi_event_watermark_lkp/type=nonbot
#      hdfs:
#        path: hdfs://apollo-router/sys/soj/ubd/events/type=nonbot
#        watermark-path: hdfs://apollo-router/sys/soj/ubd/watermark/events/type=nonbot


