kafka:
  consumer:
    data-center: LVS
    topic:
      - behavior.totalv2.sojevent-bot-lvs
    group-id:
      lvs: sojourner-total-dumper-lvs
    bootstrap-servers:
      lvs:
        - rhs-ravvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

flink:
  app:
    name: Sojourner LVS Bot Event HDFS Load Pipeline
    parallelism:
      source: 100
      sink:
        hdfs: 100
    metric:
      watermark-process-progress: sojourner-ubd-bot-event-watermark-delay-time

hdfs:
  dump:
    path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_event_dump_w/type=bot
    watermark-path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/ubi_event_watermark_lkp/type=bot