flink:
  app:
    name: Sojourner Dumper Apollo Session Metrics - Pre-Prod
    parallelism:
      source: 50
      sink: 50
    source:
      kafka:
        group-id: sojourner-dumper-apollo-session-metrics-pre-prod
        env: prod
        stream: behavior.total.new
        dc: rno
        topic:
          - behavior.total.new.session.metrics
        from-timestamp: latest
    sink:
      hdfs:
        base-path: hdfs://apollo-router/sys/soj/ubd/metrics/
        watermark-path: hdfs://apollo-router/sys/soj/ubd/watermark/metrics/
    metric:
      watermark-delay: sojourner-session-metrics-watermark-delay-time
