flink:
  app:
    name: Sojourner Dumper Staging - Non Bot Event - Zeus
    parallelism:
      source: 1
      sink: 1
    source:
      dc: slc
    sink:
      hdfs:
        path: hdfs://zeus/user/o_ubi/soj/ubd/events/type=nonbot/
        watermark-path: hdfs://zeus/user/o_ubi/soj/ubd/watermark/events/type=nonbot/

rheos:
  registry-url: https://rheos-services.qa.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: 6218c197-200e-49d7-b404-2a4dbf7595ef
      env: staging