flink:
  app:
    name: Sojourner Dumper Apollo Pre-Prod - Event
    parallelism:
      source: 1000
      sink: 1000
    source:
      kafka:
        group-id: sojourner-dumper-apollo-event-pre-prod
        env: prod
        stream: behavior.total.new
        dc: rno
        topic:
          - behavior.total.new.sojevent.nonbot
          - behavior.total.new.sojevent.bot
        from-timestamp: latest
    sink:
      hdfs:
        base-path: hdfs://apollo-router/sys/soj/ubd/events/
        watermark-path: hdfs://apollo-router/sys/soj/ubd/watermark/events/
    metric:
      watermark-delay: sojourner-event-watermark-delay-time
