flink:
  app:
    name: Sojourner Dumper Zeus Event - Staging
    parallelism:
      source:
        non-bot: 4
        bot: 4
      sink: 8
    source:
      kafka:
        group-id: sojourner-dumper-zeus-event-staging
        env: stage
        stream: behavior.totalv2
        dc: slc
        topic:
          non-bot: behavior.totalv2.sojevent-nonbot
          bot: behavior.totalv2.sojevent-bot
        start-offset: latest
    sink:
      hdfs:
        base-path: hdfs://zeus/user/o_ubi/soj/ubd/events/
        watermark-path: hdfs://zeus/user/o_ubi/soj/ubd/watermark/events/
    metric:
      watermark-delay: sojourner-event-watermark-delay-time

rheos:
  registry-url: https://rheos-services.qa.ebay.com
  client:
    auth-type: IAF
    iaf:
      id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
      secret: 6218c197-200e-49d7-b404-2a4dbf7595ef
      env: staging