kafka:
  consumer:
    stream: behavior.pulsarv2.test
    bootstrap-servers:
      slc:
        - rhs-kxwvkiaa-kfk-slc-1.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-2.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-3.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-4.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-5.rheos-streaming-prod.svc.45.tess.io:9092
    topic:
      - behavior.pulsarv2.test.topic.1
    group-id: sojourner-distributor-dumper-for-dq

flink:
  app:
    name: Sojourner Distributor Dumper for DQ
    parallelism:
      source: 60
      sink:
        hdfs: 120
    operator-name:
      source: Sojourner Custom Topic Nonbot Event Source
      pass-through: Byte To Nonbot Event
      assgin-watermark: Nonbot Event Watermark Assign
      sink:
        event: Sojourner Custom Topic Nonbot Event Sink
    uid:
      source: sojourner-custom-topic-nonbot-event-source
      pass-through: byte-to-nonbot-event
      assgin-watermark: nonbot-event-watermak-assign
      sink:
        event: sojourner-custom-topic-nonbot-event-sink
    source:
      dc: slc
    sink:
      hdfs:
        path: hdfs://apollo-rno/sys/soj/ubd/custom_topic_dq/
