kafka:
  consumer:
    topic:
      - behavior.totalv2.signature.agent

flink:
  app:
    name: Sojourner RNO Agent Signature HDFS Load Pipeline
    parallelism:
      source: 10
      sink:
        hdfs: 10
    operator-name:
      source: Sojourner Total RNO Signature Agent Source
      sink:
        signature: Sojourner Total RNO Signature Agent Sink
    uid:
      source: sojourner-total-rno-signature-agent-source
      sink:
        signature: sojourner-total-rno-signature-agent-sink

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/signatures/type=agent
    class-name: com.ebay.sojourner.common.model.BotSignature