kafka:
  consumer:
    stream: behavior.total
    topic:
      - behavior.total.sojevent.total
    group-id: sojourner-jetstream-dumper
    bootstrap-servers:
      lvs:
        - rhs-qlsvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-qlsvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-qlsvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-qlsvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-qlsvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

flink:
  app:
    name: Jetstream Non Bot Event HDFS Load Pipeline
    parallelism:
      source: 150
      sink:
        hdfs: 150
    operator-name:
      source: Jetstream Total Nonbot Event Source
      sink: Jetstream Total Nonbot Event Sink
    uid:
      source: jetstream-total-nonbot-event-source
      sink: jetstream-total-nonbot-event-sink
    source:
      dc: lvs
    sink:
      hdfs:
        path: hdfs://apollo-rno/sys/soj/ubd/jetstream_events/type=nonbot/
        class-name: com.ebay.sojourner.common.model.JetStreamOutputEvent

