kafka:
  consumer:
    stream: behavior.totalv2
    data-center: RNO
    topic:
      - behavior.totalv2.sojevent-nonbot
    group-id:
      rno: sojourner-total-dumper-rno
    bootstrap-servers:
      rno:
        - rhs-fxuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.37.tess.io:9092

    max-poll-records: 3000
    # 16MB, default value is 50MB
    fetch-max-bytes: 16777216
    # 128KB, default value is 64KB
    receive-buffer: 131072
    fetch-max-wait-ms: 100
    # 4MB, default value is 1MB
    max-partitions-fetch-bytes: 4194304
    auto-offset-reset: latest

  producer:
    stream: behavior.totalv2
    topic:
    bootstrap-servers:
      rno:
        - rhs-fxuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.37.tess.io:9092

    batch-size: 131072
    acks: 1
    linger-ms: 10
    request-timeout-ms: 60000
    retries: 3
    buffer-memory: 67108864
    compression-type: lz4
    message-key:
      session: guid
      event:
        default: guid
        key1: guid
        key2: pageId

flink:
  app:
    name: Sojourner RNO Non Bot Event HDFS Load Pipeline
    parallelism:
      source: 150
      sink:
        kafka: 100
        hdfs: 150
    checkpoint:
      data-dir: /opt/sojourner-ubd/checkpoint
      interval-ms: 300000
      timeout-ms: 900000
      min-pause-between-ms: 120000
      max-concurrent: 1
      tolerate-failure-number: 3
    metric:
      watermark-process-progress: sojourner-ubd-nonbot-event-watermark-delay-time

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/events/type=nonbot
    watermark-path: hdfs://apollo-rno/sys/soj/ubd/watermark/events/type=nonbot
