kafka:
  consumer:
    data-center: RNO
    topic:
      - behavior.totalv2.sojevent-bot
    group-id:
      lvs: sojourner-total-dumper-lvs

flink:
  app:
    name: Sojourner LVS Bot Event HDFS Load Pipeline
    parallelism:
      source: 100
      sink:
        hdfs: 100
    metric:
      watermark-process-progress: sojourner-ubd-bot-event-watermark-delay-time

hdfs:
  dump:
    path: hdfs://hercules/sys/soj/ubd/events/type=bot
    watermark-path: hdfs://hercules/sys/soj/ubd/watermark/events/type=bot