kafka:
  consumer:
    data-center: LVS
    topic:
      - behavior.totalv2.sojevent-bot
    bootstrap-servers:
      lvs:
        - rhs-ravvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

flink:
  app:
    name: Sojourner RNO Bot Event HDFS Load Pipeline
    parallelism:
      source: 50
      sink:
        hdfs: 50
    metric:
      watermark-process-progress: sojourner-ubd-bot-event-watermark-delay-time

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/events/type=bot
    watermark-path: hdfs://apollo-rno/sys/soj/ubd/watermark/events/type=bot