kafka:
  consumer:
    data-center: RNO
    stream: behavior.total.new
    topic:
      - behavior.total.new.signature.agentIp
    group-id:
      rno: sojourner-total-new-dumper
    bootstrap-servers:
      rno:
        - rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092

flink:
  app:
    name: Sojourner RNO AgentIp Signature HDFS Load Pipeline TEST
    parallelism:
      source: 10
      sink:
        hdfs: 10
    operator-name:
      source: Sojourner Total New RNO Signature Agent IP Source
      sink: Sojourner Total New RNO Signature Agent IP Sink
    uid:
      source: sojourner-total-new-rno-signature-agent-ip-source
      sink: sojourner-total-new-rno-signature-agent-ip-sink

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/test/signatures/type=agentIp
    class-name: com.ebay.sojourner.common.model.BotSignature