kafka:
  consumer:
    data-center: RNO
    topic:
      - behavior.totalv2.sojevent-bot-rno
    group-id:
      rno: sojourner-total-dumper-lvs
    bootstrap-servers:
      rno:
        - rhs-fxuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.37.tess.io:9092

flink:
  app:
    name: Sojourner LVS Bot Event HDFS Load Pipeline
    parallelism:
      source: 150
      sink:
        hdfs: 300
    operator-name:
      source: Sojourner Total LVS Bot Event Source
      pass-through: LVS Byte To Bot Event
      assgin-watermark: LVS Bot Event Watermark Assign
      extract-watermark: LVS Bot Event Timestamp Extract
      sink:
        event: Sojourner Total LVS Bot Event Sink
        watermark: Sojourner Total LVS Bot Event Watermark Sink
    uid:
      source: sojourner-total-lvs-bot-event-source
      pass-through: lvs-byte-to-bot-event
      assgin-watermark: lvs-bot-event-watermak-assign
      extract-watermark: lvs-bot-event-timestamp-extract
      sink:
        event: sojourner-total-lvs-bot-event-sink
        watermark: sojourner-total-lvs-bot-event-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-bot-event-watermark-delay-time

hdfs:
  dump:
    path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_event_dump_w/type=bot
    watermark-path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/ubi_event_watermark_lkp/type=bot

#hdfs:
#  dump:
#    path: hdfs://hercules/sys/soj/ubd/events/type=bot
#    watermark-path: hdfs://hercules/sys/soj/ubd/watermark/events/type=bot