kafka:
  consumer:
    data-center: LVS
    topic: behavior.totalv2.sojsession-nonbot
    group-id: sojourner-total-dumper-lvs
    bootstrap-servers:
      lvs:
        - rhs-ravvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

flink:
  app:
    name: Sojourner Non Bot Session HDFS Load Pipeline
    parallelism:
      source: 15
      sink:
        hdfs: 15
    metric:
      name: sojourner-ubd-nonbot-session-watermark-delay-time

hdfs:
  dump:
    path:
      open: hdfs://hercules/sys/soj/ubd/sessions/category=open/type=nonbot
      same-day: hdfs://hercules/sys/soj/ubd/sessions/category=sameday/type=nonbot
      cross-day: hdfs://hercules/sys/soj/ubd/sessions/category=crossday/type=nonbot
    watermark-path: hdfs://hercules/sys/soj/ubd/watermark/sessions/type=nonbot