kafka:
  consumer:
    topic:
      - behavior.totalv2.sojevent-bot

flink:
  app:
    name: Sojourner RNO Bot Event HDFS Load Pipeline
    parallelism:
      source: 100
      sink:
        hdfs: 100
    metric:
      watermark-process-progress: sojourner-ubd-bot-event-watermark-delay-time

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/stg_ubi_event_dump_w/type=bot
    watermark-path: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/ubi_event_watermark_lkp/type=bot