kafka:
  consumer:
    data-center: LVS
    topic:
      - behavior.totalv2.sojevent-nonbot-lvs
    group-id:
      lvs: sojourner-total-dumper-lvs
    bootstrap-servers:
      lvs:
        - rhs-ravvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

flink:
  app:
    name: Sojourner LVS Non Bot Event HDFS Load Pipeline
    operator-name:
      source: Sojourner Total LVS Nonbot Event Source
      sink:
        event: Sojourner Total LVS Nonbot Event Sink
        watermark: Sojourner Total LVS Nonbot Event Watermark Sink
    uid:
      source: sojourner-total-lvs-nonbot-event-source
      sink:
        event: sojourner-total-lvs-nonbot-event-sink
        watermark: sojourner-total-lvs-nonbot-event-watermark-sink

hdfs:
  dump:
    path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_event_dump_w/type=nonbot
    watermark-path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/ubi_event_watermark_lkp/type=nonbot