flink:
  app:
    name: Sojourner QA Non Bot Session HDFS Load Pipeline
    parallelism:
      source: 1
      sink:
        hdfs: 1
    operator-name:
      source: Sojourner QA Nonbot Session Source
      pass-through: QA Byte To Nonbot Session
      assgin-watermark: QA Nonbot Session Watermark Assign
      extract-watermark: QA Nonbot Session Timestamp Extract
      session-split: QA Nonbot Session Split
      sink:
        session:
          open: Sojourner Total QA Nonbot Open Session Sink
          same-day: Sojourner Total QA Nonbot Same Day Session Sink
          cross-day: Sojourner Total QA Nonbot Cross Day Session Sink
        watermark: Sojourner Total QA Nonbot Session Watermark Sink
    uid:
      source: sojourner-total-qa-nonbot-session-source
      pass-through: qa-byte-to-nonbot-session
      assgin-watermark: qa-nonbot-session-watermak-assign
      extract-watermark: qa-nonbot-session-timestamp-extract
      session-split: qa-nonbot-session-split
      sink:
        session:
          open: sojourner-total-qa-nonbot-open-session-sink
          same-day: sojourner-total-qa-nonbot-same-day-session-sink
          cross-day: sojourner-total-qa-nonbot-cross-day-session-sink
        watermark: sojourner-total-qa-nonbot-session-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-nonbot-session-watermark-delay-time
    source:
      dc: slc
    sink:
      hdfs:
        path:
          open: hdfs://zeus/user/o_ubi/soj/ubd/sessions/category=open/type=nonbot
          same-day: hdfs://zeus/user/o_ubi/soj/ubd/sessions/category=sameday/type=nonbot
          cross-day: hdfs://zeus/user/o_ubi/soj/ubd/sessions/category=crossday/type=nonbot
        watermark-path: hdfs://zeus/user/o_ubi/soj/ubd/watermark/sessions/type=nonbot

kafka:
  consumer:
    topic:
      - behavior.totalv2.sojsession-nonbot
    group-id: sojourner-dumper-zeus-session
    bootstrap-servers:
      slc:
        - rhs-vgnaniaa-kfk-1.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-2.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-3.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-4.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-5.rheos-streaming-qa.stratus.qa.ebay.com:9092

rheos:
  registry-url: https://rheos-services.qa.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: 6218c197-200e-49d7-b404-2a4dbf7595ef
      env: staging