flink:
  app:
    name: Sojourner Dumper Apollo Event - Pre-Prod
    parallelism:
      source:
        non-bot: 400
        bot: 600
      sink: 1200
    source:
      kafka:
        group-id: sojourner-dumper-apollo-event-dq-pre-prod
        env: prod
        stream: pulsar-placeholder-rno
        dc: rno
        topic:
          non-bot: pulsar-placeholder-rno.test.sojevent-nonbot
          bot: pulsar-placeholder-rno.test.sojevent-bot
        start-offset: latest
    sink:
      hdfs:
        base-path: hdfs://apollo-router/sys/soj/ubd/events/
        watermark-path: hdfs://apollo-router/sys/soj/ubd/watermark/events/
    metric:
      watermark-delay: sojourner-event-watermark-delay-time

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    auth-type: TRUST_FABRIC