kafka:
  consumer:
    data-center: RNO
    topic:
      - behavior.totalv2.signature.ip-rno
    group-id:
      rno: sojourner-total-dumper-rno
    bootstrap-servers:
      rno:
        - rhs-fxuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.37.tess.io:9092

flink:
  app:
    name: Sojourner RNO Ip Signature HDFS Load Pipeline
    parallelism:
      source: 10
      sink:
        hdfs: 10
    operator-name:
      source: Sojourner Total RNO Signature IP Source
      sink: Sojourner Total RNO Signature IP Sink
    uid:
      source: sojourner-total-rno-signature-ip-source
      sink: sojourner-total-rno-signature-ip-sink

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/signatures/type=ip
    class-name: com.ebay.sojourner.common.model.BotSignature