flink:
  app:
    name: Sojourner Dumper Hercules Event - Prod
    parallelism:
      source:
        non-bot: 400
        bot: 600
      sink: 1200
    source:
      kafka:
        group-id: sojourner-dumper-hercules-event-prod
        env: prod
        stream: behavior.totalv3
        dc: lvs
        topic:
          non-bot: behavior.totalv3.sojevent-nonbot-rno
          bot: behavior.totalv3.sojevent-bot-rno
        start-offset: latest
    sink:
      hdfs:
        base-path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_event_dump_w/
        watermark-path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/ubi_event_watermark_lkp/
    metric:
      watermark-delay: sojourner-event-watermark-delay-time
