kafka:
  consumer:
    stream: behavior-trafficjam
    topic:
      - behavior.trafficjam.event
    group-id:
    lvs: sojourner-pathfinder-event-non-bot-qa
    bootstrap-servers:
      lvs:
        - rhs-rurvkiaa-kfk-lvs-1.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-3.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-4.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-5.rheos-streaming-qa.svc.32.tess.io:9092

  common:
    consumer:
      max-poll-records: 3000
      receive-buffer: 8388608
      fetch-max-bytes: 262144000
      fetch-max-wait-ms: 1000
      max-partitions-fetch-bytes: 8388608
      auto-offset-reset: latest
    producer:
      batch-size: 4096
      request-timeout-ms: 60000
      message-key:
        session: guid
        event: guid

  producer:
    stream:
    topic:
    bootstrap-servers:
      rno:

flink:
  app:
    parallelism:
      source: 2
      sink:
        kafka: 2
        hdfs: 2

rheos:
  serviceUrl: https://rheos-services.qa.ebay.com
  iaf:
    secret: 6218c197-200e-49d7-b404-2a4dbf7595ef
    env: staging

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/events
    class-name: com.ebay.sojourner.common.model.SojEvent

zookeeper:
  server: rhs-tdtvkiaa-fzk-lvs-1.rheos-streaming-qa.svc.32.tess.io:2181,rhs-tdtvkiaa-fzk-lvs-2.rheos-streaming-qa.svc.32.tess.io:2181,rhs-tdtvkiaa-fzk-lvs-3.rheos-streaming-qa.svc.32.tess.io:2181,rhs-tdtvkiaa-fzk-lvs-4.rheos-streaming-qa.svc.32.tess.io:2181,rhs-tdtvkiaa-fzk-lvs-5.rheos-streaming-qa.svc.32.tess.io:2181

rest-client:
  rest-server: https://sojubdportalservice.vip.qa.ebay.com