kafka:
  consumer:
    stream: behavior.totalv3
    topic:
      - behavior.totalv3.sojevent-bot-lvs
      - behavior.totalv3.sojevent-bot-rno
    group-id: sojourner-dumper-pre-prod-totalv3lvs-apollo
    bootstrap-servers:
      rno:
        - rhs-lpdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      lvs:
        - rhs-opdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092

flink:
  app:
    name: Pre-Prod Sojourner Bot Event HDFS Load Pipeline - Totalv3-lvs -> Apollo
    parallelism:
      source: 400
      sink:
        hdfs: 500
    operator-name:
      source: Sojourner Total RNO Bot Event Source
      pass-through: RNO Byte To Bot Event
      assgin-watermark: RNO Bot Event Watermark Assign
      extract-watermark: RNO Bot Event Timestamp Extract
      sink:
        event: Sojourner Total RNO Bot Event Sink
        watermark: Sojourner Total RNO Bot Event Watermark Sink
    uid:
      source: sojourner-total-rno-bot-event-source
      pass-through: rno-byte-to-bot-event
      assgin-watermark: rno-bot-event-watermak-assign
      extract-watermark: rno-bot-event-timestamp-extract
      sink:
        event: sojourner-total-rno-bot-event-sink
        watermark: sojourner-total-rno-bot-event-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-bot-event-watermark-delay-time
    source:
      dc: lvs
    sink:
      hdfs:
        path: hdfs://apollo-router/sys/soj/ubd/events/type=bot
        watermark-path: hdfs://apollo-router/sys/soj/ubd/watermark/events/type=bot
