kafka:
  consumer:
    data-center: LVS
    topic:
      - behavior.totalv2.sojsession-bot-lvs
    group-id:
      lvs: sojourner-total-dumper-lvs
    bootstrap-servers:
      lvs:
        - rhs-ravvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

flink:
  app:
    name: Sojourner LVS Bot Session HDFS Load Pipeline
    parallelism:
      source: 20
      sink:
        hdfs: 20
    metric:
      watermark-process-progress: sojourner-ubd-bot-session-watermark-delay-time

hdfs:
  dump:
    path:
      open: hdfs://hercules/sys/soj/ubd/sessions/category=open/type=bot
      same-day: hdfs://hercules/sys/soj/ubd/sessions/category=sameday/type=bot
      cross-day: hdfs://hercules/sys/soj/ubd/sessions/category=crossday/type=bot
    watermark-path: hdfs://hercules/sys/soj/ubd/watermark/sessions/type=bot