kafka:
  consumer:
    topic:
      - behavior.totalv2.sojsession-bot-lvs

flink:
  app:
    name: Sojourner RNO Bot Session HDFS Load Pipeline
    parallelism:
      source: 50
      sink:
        hdfs: 50
    operator-name:
      source: Sojourner Total RNO Bot Session Source
      sink:
        session:
          open: Sojourner Total RNO Bot Open Session Sink
          same-day: Sojourner Total RNO Bot Same Day Session Sink
          cross-day: Sojourner Total RNO Bot Cross Day Session Sink
        watermark: Sojourner Total RNO Bot Session Watermark Sink
    uid:
      source: sojourner-total-rno-bot-session-source
      sink:
        session:
          open: sojourner-total-rno-bot-open-session-sink
          same-day: sojourner-total-rno-bot-same-day-session-sink
          cross-day: sojourner-total-rno-bot-cross-day-session-sink
        watermark: sojourner-total-rno-bot-session-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-bot-session-watermark-delay-time

hdfs:
  dump:
    path:
      open: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=open/type=bot
      same-day: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=sameday/type=bot
      cross-day: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=crossday/type=bot
    watermark-path: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/ubi_session_watermark_lkp/type=bot