kafka:
  consumer:
    topic: behavior.totalv2.sojevent-bot

flink:
  app:
    name: Sojourner Bot Event HDFS Load Pipeline
    parallelism:
      source: 50
      sink:
        hdfs: 50
    metric:
      watermark-process-progress: sojourner-ubd-bot-event-watermark-delay-time

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/events/type=bot
    watermark-path: hdfs://apollo-rno/sys/soj/ubd/watermark/events/type=bot