flink:
  app:
    checkpoint:
      data-dir: /tmp/flink/checkpoints/sojourner-dumper/
      # 5 mins
      interval-ms: 300000
      # 15 mins
      timeout-ms: 900000
    source:
      from-timestamp: latest

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    auth-type: IAF
    iaf:
      id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production