kafka:
  consumer:
    stream: behavior.pulsar
    topic:
      - behavior.pulsar.sojsession.botsession
    group-id:
      rno: sojourner-jetstream-dumper
    bootstrap-servers:
      rno:
        - rhs-okrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092

flink:
  app:
    name: Jetstream Bot Session HDFS Load Pipeline
    parallelism:
      source: 20
      sink:
        hdfs: 20
    operator-name:
      source: Jetstream Pulsar Bot Session Source
      sink: Jetstream Pulsar Bot Session Sink
    uid:
      source: jetstream-pulsar-bot-session-source
      sink: jetstream-pulsar-bot-session-sink

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/jetstream_sessions/type=bot/
    class-name: com.ebay.sojourner.common.model.JetStreamOutputSession