kafka:
  consumer:
    data-center: LVS
    topic:
      - behavior.totalv2.sojsession-nonbot-lvs
    group-id:
      lvs: sojourner-total-dumper-lvs
    bootstrap-servers:
      lvs:
        - rhs-ravvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

flink:
  app:
    name: Sojourner LVS Non Bot Session HDFS Load Pipeline
    parallelism:
      source: 50
      sink:
        hdfs: 50
    metric:
      watermark-process-progress: sojourner-ubd-nonbot-session-watermark-delay-time

hdfs:
  dump:
    path:
      open: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=open/type=nonbot
      same-day: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=sameday/type=nonbot
      cross-day: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=crossday/type=nonbot
    watermark-path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/ubi_session_watermark_lkp/type=nonbot