kafka:
  consumer:
    data-center: LVS
    topic:
      - behavior.totalv2.sojsession-nonbot-lvs
    group-id:
      lvs: sojourner-total-dumper-lvs
    bootstrap-servers:
      lvs:
        - rhs-ravvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

flink:
  app:
    name: Sojourner LVS Non Bot Session HDFS Load Pipeline
    parallelism:
      source: 50
      sink:
        hdfs: 50
    operator-name:
      source: Sojourner Total LVS Nonbot Session Source
      sink:
        session:
          open: Sojourner Total LVS Nonbot Open Session Sink
          same-day: Sojourner Total LVS Nonbot Same Day Session Sink
          cross-day: Sojourner Total LVS Nonbot Cross Day Session Sink
        watermark: Sojourner Total LVS Nonbot Session Watermark Sink
    uid:
      source: sojourner-total-lvs-nonbot-session-source
      sink:
        session:
          open: sojourner-total-lvs-nonbot-open-session-sink
          same-day: sojourner-total-lvs-nonbot-same-day-session-sink
          cross-day: sojourner-total-lvs-nonbot-cross-day-session-sink
        watermark: sojourner-total-lvs-nonbot-session-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-nonbot-session-watermark-delay-time

hdfs:
  dump:
    path:
      open: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=open/type=nonbot
      same-day: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=sameday/type=nonbot
      cross-day: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=crossday/type=nonbot
    watermark-path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/ubi_session_watermark_lkp/type=nonbot