flink:
  app:
    name: Sojourner QA Bot Session HDFS Load Pipeline
    parallelism:
      source: 1
      sink:
        hdfs: 1
    operator-name:
      source: Sojourner QA Bot Session Source
      pass-through: QA Byte To Bot Session
      assgin-watermark: QA Bot Session Watermark Assign
      extract-watermark: QA Bot Session Timestamp Extract
      session-split: QA Bot Session Split
      sink:
        session:
          open: Sojourner Total QA Bot Open Session Sink
          same-day: Sojourner Total QA Bot Same Day Session Sink
          cross-day: Sojourner Total QA Bot Cross Day Session Sink
        watermark: Sojourner Total QA Bot Session Watermark Sink
    uid:
      source: sojourner-total-qa-bot-session-source
      pass-through: qa-byte-to-bot-session
      assgin-watermark: qa-bot-session-watermak-assign
      extract-watermark: qa-bot-session-timestamp-extract
      session-split: qa-bot-session-split
      sink:
        session:
          open: sojourner-total-qa-bot-open-session-sink
          same-day: sojourner-total-qa-bot-same-day-session-sink
          cross-day: sojourner-total-qa-bot-cross-day-session-sink
        watermark: sojourner-total-qa-bot-session-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-bot-session-watermark-delay-time
    source:
      dc: slc
    sink:
      hdfs:
        path:
          open: hdfs://zeus/user/o_ubi/soj/ubd/sessions/category=open/type=bot
          same-day: hdfs://zeus/user/o_ubi/soj/ubd/sessions/category=sameday/type=bot
          cross-day: hdfs://zeus/user/o_ubi/soj/ubd/sessions/category=crossday/type=bot
        watermark-path: hdfs://zeus/user/o_ubi/soj/ubd/watermark/sessions/type=bot

kafka:
  consumer:
    topic:
      - behavior.totalv2.sojsession-bot
    group-id: sojourner-dumper-zeus-session
    bootstrap-servers:
      slc:
        - rhs-vgnaniaa-kfk-1.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-2.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-3.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-4.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-5.rheos-streaming-qa.stratus.qa.ebay.com:9092

rheos:
  registry-url: https://rheos-services.qa.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: 6218c197-200e-49d7-b404-2a4dbf7595ef
      env: staging