kafka:
  consumer:
    topic:
      - behavior.totalv2.signature.agent-ip

flink:
  app:
    name: Sojourner RNO AgentIp Signature HDFS Load Pipeline
    parallelism:
      source: 10
      sink:
        hdfs: 10
    operator-name:
      source: Sojourner Total RNO Signature Agent IP Source
      sink:
        signature: Sojourner Total RNO Signature Agent IP Sink
    uid:
      source: sojourner-total-rno-signature-agent-ip-source
      sink:
        signature: sojourner-total-rno-signature-agent-ip-sink

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/signatures/type=agentIp
    class-name: com.ebay.sojourner.common.model.BotSignature