kafka:
  consumer:
    data-center: LVS
    topic:
      - behavior.totalv2.signature.agent-lvs
    group-id:
      lvs: sojourner-total-dumper-lvs
    bootstrap-servers:
      lvs:
        - rhs-ravvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

flink:
  app:
    name: Sojourner LVS Agent Signature HDFS Load Pipeline
    parallelism:
      source: 10
      sink:
        hdfs: 10
    operator-name:
      source: Sojourner Total LVS Signature Agent Source
      sink: Sojourner Total LVS Signature Agent Sink
    uid:
      source: sojourner-total-lvs-signature-agent-source
      sink: sojourner-total-lvs-signature-agent-sink

hdfs:
  dump:
    path: hdfs://hercules/sys/soj/ubd/signatures/type=agent
    class-name: com.ebay.sojourner.common.model.BotSignature