kafka:
  consumer:
    topic:
      - behavior.totalv2.sojsession-nonbot

flink:
  app:
    name: Sojourner RNO Non Bot Session HDFS Load Pipeline
    parallelism:
      source: 15
      sink:
        hdfs: 15
    metric:
      watermark-process-progress: sojourner-ubd-nonbot-session-watermark-delay-time

hdfs:
  dump:
    path:
      open: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=open/type=nonbot
      same-day: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=sameday/type=nonbot
      cross-day: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=crossday/type=nonbot
    watermark-path: hdfs://apollo-rno/sys/edw/working/ubi/ubi_w/soj/ubi_session_watermark_lkp/type=nonbot