kafka:
  consumer:
    stream: behavior.totalv3
    topic:
      - behavior.totalv3.sojsession-bot-lvs
      - behavior.totalv3.sojsession-bot-rno
    group-id: sojourner-dumper-pre-prod-totalv3lvs-apollo
    bootstrap-servers:
      rno:
        - rhs-lpdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      lvs:
        - rhs-opdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092

flink:
  app:
    name: Pre-Prod Sojourner Bot Session HDFS Load Pipeline - Totalv3-lvs -> Apollo
    parallelism:
      source: 50
      sink:
        hdfs: 50
    operator-name:
      source: Sojourner Total RNO Bot Session Source
      pass-through: RNO Byte To Bot Session
      assgin-watermark: RNO Bot Session Watermark Assign
      extract-watermark: RNO Bot Session Timestamp Extract
      session-split: RNO Bot Session Split
      sink:
        session:
          open: Sojourner Total RNO Bot Open Session Sink
          same-day: Sojourner Total RNO Bot Same Day Session Sink
          cross-day: Sojourner Total RNO Bot Cross Day Session Sink
        watermark: Sojourner Total RNO Bot Session Watermark Sink
    uid:
      source: sojourner-total-rno-bot-session-source
      pass-through: rno-byte-to-bot-session
      assgin-watermark: rno-bot-session-watermak-assign
      extract-watermark: rno-bot-session-timestamp-extract
      session-split: rno-bot-session-split
      sink:
        session:
          open: sojourner-total-rno-bot-open-session-sink
          same-day: sojourner-total-rno-bot-same-day-session-sink
          cross-day: sojourner-total-rno-bot-cross-day-session-sink
        watermark: sojourner-total-rno-bot-session-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-bot-session-watermark-delay-time
    source:
      dc: lvs
    sink:
      hdfs:
        path:
          open: hdfs://apollo-router/sys/soj/ubd/sessions/category=open/type=bot
          same-day: hdfs://apollo-router/sys/soj/ubd/sessions/category=sameday/type=bot
          cross-day: hdfs://apollo-router/sys/soj/ubd/sessions/category=crossday/type=bot
        watermark-path: hdfs://apollo-router/sys/soj/ubd/watermark/sessions/type=bot
