kafka:
  consumer:
    stream: behavior.total.new
    topic: behavior.total.new.sojevent
    group-id: sojourner-total-dumper-test
    bootstrap-servers:
      rno:
        - rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092

hdfs:
  dump:
    path: hdfs://apollo-rno/sys/soj/ubd/test/events/type=nonbot
    watermark-path: hdfs://apollo-rno/sys/soj/ubd/test/watermark/events/type=nonbot