kafka:
  consumer:
    topic:
      - behavior.totalv2.sojsession-nonbot-rno
    group-id: sojourner-total-dumper-lvs

flink:
  app:
    name: Sojourner LVS Non Bot Session HDFS Load Pipeline
    parallelism:
      source: 50
      sink:
        hdfs: 50
    operator-name:
      source: Sojourner Total LVS Nonbot Session Source
      pass-through: LVS Byte To Nonbot Session
      assgin-watermark: LVS Nonbot Session Watermark Assign
      extract-watermark: LVS Nonbot Session Timestamp Extract
      session-split: LVS Nonbot Session Split
      sink:
        session:
          open: Sojourner Total LVS Nonbot Open Session Sink
          same-day: Sojourner Total LVS Nonbot Same Day Session Sink
          cross-day: Sojourner Total LVS Nonbot Cross Day Session Sink
        watermark: Sojourner Total LVS Nonbot Session Watermark Sink
    uid:
      source: sojourner-total-lvs-nonbot-session-source
      pass-through: lvs-byte-to-nonbot-session
      assgin-watermark: lvs-nonbot-session-watermak-assign
      extract-watermark: lvs-nonbot-session-timestamp-extract
      session-split: lvs-nonbot-session-split
      sink:
        session:
          open: sojourner-total-lvs-nonbot-open-session-sink
          same-day: sojourner-total-lvs-nonbot-same-day-session-sink
          cross-day: sojourner-total-lvs-nonbot-cross-day-session-sink
        watermark: sojourner-total-lvs-nonbot-session-watermark-sink
    metric:
      watermark-process-progress: sojourner-ubd-nonbot-session-watermark-delay-time
    source:
      dc: rno
    sink:
      hdfs:
        path:
          open: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=open/type=nonbot
          same-day: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=sameday/type=nonbot
          cross-day: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=crossday/type=nonbot
        watermark-path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/ubi_session_watermark_lkp/type=nonbot
#      hdfs:
#        path:
#          open: hdfs://hercules/sys/soj/ubd/sessions/category=open/type=nonbot
#          same-day: hdfs://hercules/sys/soj/ubd/sessions/category=sameday/type=nonbot
#          cross-day: hdfs://hercules/sys/soj/ubd/sessions/category=crossday/type=nonbot
#        watermark-path: hdfs://hercules/sys/soj/ubd/watermark/sessions/type=nonbot


