kafka:
  consumer:
    data-center: RNO
    topic:
      - behavior.totalv2.sojsession-bot-lvs
    group-id:
      lvs: sojourner-total-dumper-lvs

flink:
  app:
    name: Sojourner LVS Bot Session HDFS Load Pipeline
    parallelism:
      source: 50
      sink:
        hdfs: 50
    metric:
      watermark-process-progress: sojourner-ubd-bot-session-watermark-delay-time

hdfs:
  dump:
    path:
      open: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=open/type=bot
      same-day: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=sameday/type=bot
      cross-day: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/stg_ubi_session_dump_w/category=crossday/type=bot
    watermark-path: hdfs://hercules/sys/edw/working/ubi/ubi_w/soj/ubi_session_watermark_lkp/type=bot