kafka:
  consumer:
    stream: behavior.pulsar
    bootstrap-servers:
      rno:
        - rhs-okrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
      slc:
        - rhs-qisvkiaa-kfk-slc-1.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-qisvkiaa-kfk-slc-2.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-qisvkiaa-kfk-slc-3.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-qisvkiaa-kfk-slc-4.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-qisvkiaa-kfk-slc-5.rheos-streaming-prod.svc.45.tess.io:9092
    topic:
      - behavior.pulsar.event.search
    group-id: sojourner-dumper-test-js-search

flink:
  app:
    name: Sojourner Dumper for JetStream Search Event
    parallelism:
      source: 60
      sink:
        hdfs: 120
    operator-name:
      source: JetStream Pulsar search event Source
      sink: JetStream Pulsar search event Sink
    uid:
      source: jetstream-pulsar-search-event-source
      sink: jetstream-pulsar-search-event-sink
    source:
      dc: rno
    sink:
      hdfs:
        path: hdfs://apollo-rno/sys/soj/ubd/distributor_dq_jetstream_search
        class-name: com.ebay.sojourner.common.model.PulsarEvent