package com.ebay.sojourner.business.metric;

import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertFalse;

import com.ebay.sojourner.common.model.UbiEvent;
import com.ebay.sojourner.common.util.IosEventFilter;
import org.junit.Test;

public class IosEventFilterTest {

  @Test
  public void isIosEvent() {

    assertTrue(IosEventFilter.isIosEvent("ebayUserAgent/eBayIOS;6.115.0;iOS;16.5.1;Apple;iPhone14_2;voda AU;390x844;3.0"));
    assertFalse(IosEventFilter.isIosEvent("ebayUserAgent/eBayAndroid;6.115.0;Android;13;samsung;y2q;Fido;1080x2192;2.8;"));
    assertFalse(IosEventFilter.isIosEvent("Mozilla/5.0 (iPhone; CPU iPhone OS 16_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Mobile/15E148 Safari/604.1"));
  }

  @Test
  public void isValidIosEvent() {
    UbiEvent event = new UbiEvent();
    event.setAppId(1462);
    event.setApplicationPayload("nqc=CAgAAAAAAAAAiAAQAACAAAgAAAAAAAgACAAAAAAACCAQAAAIAAAAACEABAAAAEAAAAAAAAEAAAAAAAAAAAAAAAAAgASAAAAAAAAgAAAAAAAAAAAAIAAAAAAAAAAAABAABgAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAEABAAACAAAAAAAEAAAgAAAAAAAAAAAAAAAEACBQAAAAAAEACCAAAAAABAAACAAAAAAEAAIAAAAAAAAAAAIAAABAAAABAAAAIAAAAggAAAAgAAAACgAAAAAAEAAAAAAAAAAAAAAAAAAAAAQAgAAAQAQAAAIAAAgAAAAAVMoJAAAAAAAAAAAAAAAAAAAAAAEAAAAACAAAAAAgAgAAiAAIAAgAEAAAAAAAACAAAAAAAAAAAAAAQAAAAACAAACBAAAEAIAAglQACAAgEAQABAAAAEAAIAhAAAAAABAAQIAAASAAAAACggAIAABAQkAAAAAAAAgAAAAAAAAKAAAAgA**&flgs=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAg*&botFlags=&dm=Apple&dn=iPhone13_3&experience=wwHCpmS10Jw/GDQwMUg1Q0Y5M1oyMENUWjc5TVFFTjhCUVNKUDQwMUg1Q0Y5M1oyMENUWjc5TVFFTjhCUVNKUAAAAA==&schemaversion=null&uc=1&nqt=CAgAAAAAAAAAiAAQAACAAAgAAAAAAAgACAAAAAAACCAQAAAIAAAAACEABAAAAEAAAAAAAAEAAAAAABAAAAAAAAAAgASAAAAAAAAgAAAAAAAAAAAAIAAAAAAAAAAAABAABgAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAEABAAACAAAAAAAEAAAgAAAAAAAAAAAAAAAEACBQAAAAAAEAGCAAAAAABAAACAAAAAAEAAIAAAAAAAAAAAIAAABAAAABAAAAIAAAAggAAAAgAAAACgAAAAAAEAAAAAAAAAAAAAAAAAAAAAQAgAAAQAQAAAIAAAgAAAAAVMoJAAAAAAAAAAAAAAAAAAAAAAEAAAAACAAAAAAgAgAAiAAIAAgAEAAAAAAAACAAAAAAAAAAAAAAQAAAAACAAACBAEAEAIAAglQACAAgEAQABAAAAEAAIAhAAAAAABAAQIAAASAAAAACggAIAABAQkAAAAAAAAgAAAAAAAAKAAAAgA**&mos=iOS&bs=0&serviceEventId=01H5CF93Z20CTZ79MQEN8BQSJP&osv=16.5.1&SA2S_BUILD_VERSION=3.0.248-RELEASE&ul=en-US&callingpagename=searchsvc__experience_search_v1_get_search_result_GET&ec=5&epcontext=wwGOh78BE7LmFooOxgEAAAAAAAAAAAAA&pagename=searchsvc__experience_search_v1_get_search_result_GET&app=1462&res=0x0&uit=1684022996000&efam=LST&mav=6.117.0&eprlogid=t6fuuq%2560%253F%253Cumjcwpse*t3%253Fj1%2528rbpv67%253A1-18958f48fe5-0x103&g=b09cb84b18079c1cc0f4d320015906b0&h=4b&serviceCorrelationId=01H5CF93Z20CTZ79MQEN8BQSJP&devicetimestamp=2023-07-15T09:49:29.488Z&an=eBayIOS&cp=2351460&nativeApp=true&es=0&ciid=9I%252Fii10*&p=2351460&mdbreftime=0&t=0&complexTagNames=experience,epcontext&u=2257602860&cflgs=AA**&eactn=EXPC&pn=2&rq=2d546205d655d92d");
    event.setPageId(2351460);
    event.setAgentInfo("ebayUserAgent/eBayIOS;6.117.0;iOS;16.5.1;Apple;iPhone13_3;--;390x844;3.0");

    assertFalse(IosEventFilter.isValidIosEvent(event));
  }
}