flink:
  app:
    name: Sojourner Non-Bot Event Distributor - Prod - LVS
    parallelism:
      source: 200
      filter: 200
      sink-kafka: 200
    source:
      dc: lvs
      operator-name: Non-bot SojEvent Source
    sink:
      dc: slc
      operator-name: Non-bot SojEvent Sink
    dist:
      topic-config:
        - "dss-gro:behavior.pulsar.customized.dss-gro"
        - "dss-ads-pvp-hsa:behavior.pulsar.customized.ads-pvp-hsa"
        - "srch-lst:behavior.pulsar.event.lst-srch"
        - "entry-page:behavior.pulsar.sojsession.entrypage"
        - "mt-mobile-mc3ur:behavior.pulsar.customized.mc3ur"
        - "expc-native-events:behavior.pulsar.customized.expc-native-events"
        - "srch-auto-complete:behavior.pulsar.customized.srch-auto-complete"
        - "srpGist:behavior.pulsar.customized.srpGist"
        - "expm-native-events:behavior.pulsar.customized.expm-native-events"
        - "scandal-trk:behavior.pulsar.customized.scandal-trk"
        - "viewport:behavior.pulsar.customized.viewport"
        - "new-tracking-standard:behavior.pulsar.customized.new-tracking-standard"

kafka:
  consumer:
    stream: behavior.totalv3
    group-id: sojourner-distributor-prod-lvs
    topic:
      - behavior.totalv3.sojevent-nonbot-rno
      - behavior.totalv3.sojevent-nonbot-lvs
    bootstrap-servers:
      rno:
        - rhs-lpdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      lvs:
        - rhs-opdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092

rest-client:
  config:
    profile: prod-pulsar-slc
