flink:
  app:
    name: Sojourner Bot Event Distributor - Prod - LVS
    parallelism:
      source: 200
      sink-kafka: 200
    source:
      dc: lvs
      operator-name: Bot SojEvent Source
    sink:
      dc: slc
      operator-name: Bot SojEvent Sink
    dist:
      topic-config:
        - ""

kafka:
  consumer:
    group-id: sojourner-distributor-prod-lvs
    topic:
      - behavior.totalv2.sojevent-bot-rno
      - behavior.totalv2.sojevent-bot-lvs

rest-client:
  config:
    profile: prod-bot