flink:
  app:
    name: Sojourner HA Distributor Staging - Non-Bot Event
    parallelism:
      source: 4
      sink: 4
    source:
      kafka:
        group-id: sojourner-ha-distributor-staging
        env: stage
        stream: behavior.totalv2
        dc: slc
        topic:
          - behavior.totalv2.sojevent-nonbot
        from-timestamp: latest
    filter:
      large-message:
        max-bytes: 819200
    dist:
      ha:
        producer-name: sojourner-ha-producer-staging
        probe-interval-min: 5

rheos:
  ha-service-url: https://rhs-kafka-discovery.qa.ebay.com
  client:
    auth-type: IAF
    iaf:
      id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
      secret: 6218c197-200e-49d7-b404-2a4dbf7595ef
      env: staging

rest-client:
  base-url: https://sojsvc.vip.qa.ebay.com
  config:
    profile: staging
