flink:
  app:
    name: Sojourner Distributor Bot Event - Prod
    parallelism:
      source: 600
      sink: 600
    source:
      kafka:
        group-id: sojourner-distributor-event-pulsarslc-prod
        env: prod
        stream: behavior.totalv3
        dc: lvs
        topic:
          - behavior.totalv3.sojevent-bot-rno
        from-timestamp: latest
    sink:
      kafka:
        env: prod
        stream: behavior.pulsar
        dc: slc
    filter:
      large-message:
        max-bytes: 819200
    dist:
      topic-config:
        - ""

rest-client:
  config:
    profile: prod-bot-pulsar-slc
