flink:
  app:
    name: Sojourner Distributor - PRE PROD BOT
    parallelism:
      source: 150
      sink-kafka: 150
    source:
      dc: lvs
      operator-name: Bot SojEvent Source
    sink:
      dc: slc
      operator-name: Bot SojEvent Sink
      kafka:
        topic: behavior.pulsarv2.test.default
    dist:
      topic-config:
        - "entry-page:behavior.pulsarv2.test.sojsession.entrypage"

kafka:
  consumer:
    stream: behavior.totalv2
    group-id: sojourner-distributor-pre-prod
    topic:
      - behavior.totalv2.sojevent-bot-rno
      - behavior.totalv2.sojevent-bot-lvs
    bootstrap-servers:
      rno:
        - rhs-fxuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.37.tess.io:9092
        - rhs-fxuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.37.tess.io:9092
      lvs:
        - rhs-ravvkiaa-kfk-lvs-1.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-2.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-3.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-4.rheos-streaming-prod.svc.38.tess.io:9092
        - rhs-ravvkiaa-kfk-lvs-5.rheos-streaming-prod.svc.38.tess.io:9092

  producer:
    stream: behavior.pulsarv2.test
    bootstrap-servers:
      slc:
        - rhs-kxwvkiaa-kfk-slc-1.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-2.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-3.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-4.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-5.rheos-streaming-prod.svc.45.tess.io:9092

rest-client:
  config:
    profile: pre-prod-bot
