flink:
  app:
    name: Sojourner Distributor Non-Bot Event - Prod
    parallelism:
      source: 400
      sink: 400
    source:
      kafka:
        group-id: sojourner-distributor-event-pulsarslc-prod
        env: prod
        stream: behavior.totalv3
        dc: lvs
        topic:
          - behavior.totalv3.sojevent-nonbot-rno
        start-offset: latest
    sink:
      kafka:
        env: prod
        stream: behavior.pulsar
        dc: slc
    filter:
      large-message:
        max-bytes: 819200
    dist:
      topic-config:
        - "entry-page:behavior.pulsar.sojsession.entrypage"
        - "mt-mobile-mc3ur:behavior.pulsar.customized.mc3ur"
        - "expc-native-events:behavior.pulsar.customized.expc-native-events"
        - "srch-auto-complete:behavior.pulsar.customized.srch-auto-complete"
        - "srpGist:behavior.pulsar.customized.srpGist"
        - "expm-native-events:behavior.pulsar.customized.expm-native-events"
        - "new-tracking-standard:behavior.pulsar.customized.new-tracking-standard"

rest-client:
  config:
    profile: prod-pulsar-slc
