flink:
  app:
    name: Sojourner Session Distributor - PRE PROD
    parallelism:
      source: 50
      sink-kafka: 50
    source:
      dc: rno
      operator-name: Non-bot SojSession Source
    sink:
      dc: slc
      operator-name: Non-bot SojSession Sink
      kafka:
        topic: behavior.pulsarv2.test.session-nonbot

kafka:
  consumer:
    stream: behavior.total.new
    group-id: sojourner-distributor-pre-prod
    topic:
      - behavior.total.new.sojsession
    bootstrap-servers:
      rno:
        - rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092

  producer:
    stream: behavior.pulsarv2.test
    bootstrap-servers:
      slc:
        - rhs-kxwvkiaa-kfk-slc-1.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-2.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-3.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-4.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-kxwvkiaa-kfk-slc-5.rheos-streaming-prod.svc.45.tess.io:9092
