flink:
  app:
    name: Sojourner Bot Event Distributor - Prod - RNO
    parallelism:
      source: 200
      filter: 200
      sink-kafka: 200
    source:
      dc: rno
      operator-name: Bot SojEvent Source
    sink:
      dc: rno
      operator-name: Bot SojEvent Sink
    dist:
      topic-config:
        - "scandal-trk:behavior.pulsar.customized.scandal-trk.bot"
        - "viewport:behavior.pulsar.customized.viewport.bot"

kafka:
  consumer:
    group-id: sojourner-distributor-prod-rno
    topic:
      - behavior.totalv2.sojevent-bot-rno
      - behavior.totalv2.sojevent-bot-lvs

rest-client:
  config:
    profile: prod-bot