flink:
  app:
    name: Sojourner Distributor Non-Bot Event - Prod
    parallelism:
      source: 400
      sink: 400
    source:
      kafka:
        group-id: sojourner-distributor-event-pulsarrno-prod
        env: prod
        stream: behavior.totalv3
        dc: rno
        topic:
          - behavior.totalv3.sojevent-nonbot-rno
        start-offset: latest
    sink:
      kafka:
        env: prod
        stream: behavior.pulsar
        dc: rno
    filter:
      large-message:
        max-bytes: 819200
    dist:
      topic-config:
        - "dss-gro:behavior.pulsar.customized.dss-gro"
        - "mt-mobile-mc3ur:behavior.pulsar.customized.mc3ur"
        - "srch-auto-complete:behavior.pulsar.customized.srch-auto-complete"
        - "srpGist:behavior.pulsar.customized.srpGist"
        - "scandal-trk:behavior.pulsar.customized.scandal-trk"
        - "viewport:behavior.pulsar.customized.viewport"
        - "new-tracking-standard:behavior.pulsar.customized.new-tracking-standard"

rest-client:
  config:
    profile: prod-pulsar-rno
