flink:
  app:
    checkpoint:
      data-dir: /tmp/flink/checkpoints/sojourner-distributor/
      interval-ms: 300000
      timeout-ms: 600000

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    auth-type: IAF
    iaf:
      id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
      secret: c4bb6fca-7ac5-46dd-b218-a49cb6307dbc
      env: production

kafka:
  consumer:
    # 5000, default is 500
    max-poll-records: 5000
    # 50MB, default value is 50MB
    fetch-max-bytes: 52428800
    # 1MB, default value is 64KB
    receive-buffer: 1048576
    # 100ms, default value is 500ms
    fetch-max-wait-ms: 100
    # 10MB, default value is 1MB
    max-partitions-fetch-bytes: 10485760
    # when offset cannot be found, read from `latest`
    auto-offset-reset: latest
  
  producer:
    # 1MB, default value is 16KB
    batch-size: 1048576
    # 50ms, default value is 0
    linger-ms: 50
    # 30s, default value is 30s
    request-timeout-ms: 30000
    # 10, default value is 2147483647
    retries: 10
    # 256MB, default value is 32MB
    buffer-memory: 268435456
    # default value is none
    compression-type: lz4
    # 5m, default value is 120s
    delivery-timeout-ms: 300000
    # 1000000 bytes, default value is 1MB
    max-request-size: 1000000

rest-client:
  base-url: https://sojsvc.vip.ebay.com
  config:
    profile: prod
