flink:
  app:
    name: Sojourner Bot Event Distributor - Staging
    parallelism:
      source: 4
      sink-kafka: 4
    checkpoint:
      data-dir: /tmp/flink/sojourner/distributor/checkpoint
    source:
      dc: slc
      operator-name: Bot SojEvent Source
    sink:
      dc: slc
      operator-name: Bot SojEvent Sink
      kafka:
        topic: behavior.pulsar.sojevent.deadletter
    dist:
      topic-config:
        - "scandal-trk:behavior.pulsar.customized.scandal-trk.bot"

kafka:
  consumer:
    stream: behavior.totalv2
    group-id: sojourner-distributor-staging
    topic:
      - behavior.totalv2.sojevent-bot
    bootstrap-servers:
      lvs:
        - rhs-rurvkiaa-kfk-lvs-1.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-3.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-4.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-5.rheos-streaming-qa.svc.32.tess.io:9092
      slc:
        - rhs-vgnaniaa-kfk-1.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-2.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-3.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-4.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-5.rheos-streaming-qa.stratus.qa.ebay.com:9092

    max-poll-records: 500
    # 50MB, default value is 50MB
    fetch-max-bytes: 52428800
    # 128KB, default value is 64KB
    receive-buffer: 131072
    fetch-max-wait-ms: 100
    # 1MB, default value is 1MB
    max-partitions-fetch-bytes: 1048576
    auto-offset-reset: latest

  producer:
    stream: behavior.pulsar
    bootstrap-servers:
      lvs:
        - rhs-nbrvkiaa-kfk-lvs-1.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-nbrvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-nbrvkiaa-kfk-lvs-3.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-nbrvkiaa-kfk-lvs-4.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-nbrvkiaa-kfk-lvs-5.rheos-streaming-qa.svc.32.tess.io:9092
      slc:
        - rhs-rbrvkiaa-kfk-1.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-rbrvkiaa-kfk-2.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-rbrvkiaa-kfk-3.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-rbrvkiaa-kfk-4.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-rbrvkiaa-kfk-5.rheos-streaming-qa.stratus.qa.ebay.com:9092

    # 16KB
    batch-size: 16384
    acks: 1
    linger-ms: 10
    # 30s
    request-timeout-ms: 30000
    retries: 30
    # 32MB
    buffer-memory: 33554432
    compression-type: lz4
    # 2min
    delivery-timeout-ms: 120000

rheos:
  registry-url: https://rheos-services.qa.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: 6218c197-200e-49d7-b404-2a4dbf7595ef
      env: staging

rest-client:
  base-url: https://sojsvc.vip.qa.ebay.com
#  base-url: http://localhost:8080
  username: soj-flink-app
  config:
    pull-interval: 15000
    profile: staging-bot
