flink:
  app:
    name: Sojourner Distributor Bot Event - Prod
    parallelism:
      source: 300
      sink: 300
    source:
      kafka:
        group-id: sojourner-distributor-event-pulsarrno-prod
        env: prod
        stream: behavior.totalv3
        dc: rno
        topic:
          - behavior.totalv3.sojevent-bot-rno
        start-offset: latest
    sink:
      kafka:
        env: prod
        stream: behavior.pulsar
        dc: rno
    filter:
      large-message:
        max-bytes: 819200
    dist:
      topic-config:
        - ""

rest-client:
  config:
    profile: prod-bot-pulsar-rno
