flink:
  app:
    name: Sojourner Distributor Non-Bot Session - Pre-Prod
    parallelism:
      source: 50
      sink: 50
    source:
      kafka:
        group-id: sojourner-distributor-session-pre-prod
        env: prod
        stream: behavior.total.new
        dc: rno
        topic:
          - behavior.total.new.sojsession.nonbot
        from-timestamp: latest
    sink:
      kafka:
        env: prod
        stream: behavior.total.new
        dc: rno
    dist:
      topic: behavior.total.new.sojsession.nonbot.test
