flink:
  app:
    name: Sojourner Non-Bot Event Distributor - Prod - RNO
    parallelism:
      source: 200
      filter: 200
      sink-kafka: 200
    source:
      dc: rno
      operator-name: Non-bot SojEvent Source
    sink:
      dc: rno
      operator-name: Non-bot SojEvent Sink
    dist:
      topic-config:
        - "dss-gro:behavior.pulsar.customized.dss-gro"
        - "mt-mobile-mc3ur:behavior.pulsar.customized.mc3ur"
        - "srch-auto-complete:behavior.pulsar.customized.srch-auto-complete"
        - "srpGist:behavior.pulsar.customized.srpGist"
        - "scandal-trk:behavior.pulsar.customized.scandal-trk"
        - "viewport:behavior.pulsar.customized.viewport"
        - "new-tracking-standard:behavior.pulsar.customized.new-tracking-standard"

kafka:
  consumer:
    stream: behavior.totalv3
    group-id: sojourner-distributor-prod-rno
    topic:
      - behavior.totalv3.sojevent-nonbot-rno
      - behavior.totalv3.sojevent-nonbot-lvs
    bootstrap-servers:
      rno:
        - rhs-lpdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      lvs:
        - rhs-opdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092

rest-client:
  config:
    profile: prod-pulsar-rno
