flink:
  app:
    name: Sojourner Non-Bot Event Distributor - Prod - LVS --HA
    parallelism:
      source: 200
      filter: 200
      sink-kafka: 200
    source:
      dc: lvs
      operator-name: Non-bot SojEvent Source
    sink:
      dc: slc
      operator-name: Non-bot SojEvent Sink

kafka:
  consumer:
    stream: behavior.totalv3
    group-id: sojourner-distributor-prod-lvs-ha
    topic:
      - behavior.totalv3.sojevent-nonbot-rno
      - behavior.totalv3.sojevent-nonbot-lvs
    bootstrap-servers:
      rno:
        - rhs-lpdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      lvs:
        - rhs-opdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
  producer:
    probe-interval-min: 5
    producerId: sojourner-ha-producer
    stream: behavior.pulsar.dr
    bootstrap-servers:
      rno:
        - rhs-eaewkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-eaewkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-eaewkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-eaewkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-eaewkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      slc:
        - rhs-baewkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-baewkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-baewkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-baewkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-baewkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
rest-client:
  config:
    profile: ha-prod
rheos:
  ha-service-url: https://rhs-kafka-discovery.vip.ebay.com