flink:
  app:
    name: Sojourner Non-Bot Event Distributor - Prod - LVS --HA-staging
    parallelism:
      source: 2
      filter: 2
      sink-kafka: 2
    source:
      dc: slc
      operator-name: Non-bot SojEvent Source
    sink:
      dc: slc
      operator-name: Non-bot SojEvent Sink
kafka:
  consumer:
    stream: behavior.totalv2
    group-id: sojourner-distributor-prod-lvs-ha-staging
    topic:
      - behavior.totalv2.sojevent-nonbot
    bootstrap-servers:
      lvs:
        - rhs-rurvkiaa-kfk-lvs-1.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-2.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-3.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-4.rheos-streaming-qa.svc.32.tess.io:9092
        - rhs-rurvkiaa-kfk-lvs-5.rheos-streaming-qa.svc.32.tess.io:9092
      slc:
        - rhs-vgnaniaa-kfk-1.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-2.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-3.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-4.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-vgnaniaa-kfk-5.rheos-streaming-qa.stratus.qa.ebay.com:9092
    max-poll-records: 500
    # 50MB, default value is 50MB
    fetch-max-bytes: 52428800
    # 128KB, default value is 64KB
    receive-buffer: 131072
    fetch-max-wait-ms: 100
    # 1MB, default value is 1MB
    max-partitions-fetch-bytes: 1048576
    auto-offset-reset: latest
  producer:
    probe-interval-min: 5
    producerId: sojourner-ha-producer-staging
    stream: behavior.pulsar.dr
    bootstrap-servers:
      lvs:
        - rhs-ogoaniaa-kfk-1.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-ogoaniaa-kfk-2.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-ogoaniaa-kfk-3.rheos-streaming-qa.stratus.qa.ebay.com:9092
      slc:
        - rhs-ngoaniaa-kfk-1.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-ngoaniaa-kfk-2.rheos-streaming-qa.stratus.qa.ebay.com:9092
        - rhs-ngoaniaa-kfk-3.rheos-streaming-qa.stratus.qa.ebay.com:9092
rest-client:
  base-url: https://sojsvc.vip.qa.ebay.com
  #  base-url: http://localhost:8080
  username: soj-flink-app
  config:
    pull-interval: 15000
    profile: ha-staging
rheos:
  registry-url: https://rheos-services.qa.ebay.com
  ha-service-url: https://rhs-kafka-discovery.qa.ebay.com
  client:
    id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
    iaf:
      secret: 6218c197-200e-49d7-b404-2a4dbf7595ef
      env: staging