flink:
  app:
    name: Pre-Prod Non-Bot Event Distributor - Totalv3-rno -> Pulsar-slc
    parallelism:
      source: 200
      filter: 200
      sink-kafka: 200
    source:
      dc: rno
      operator-name: Non-bot SojEvent Source
    sink:
      dc: slc
      operator-name: Non-bot SojEvent Sink
      kafka:
        topic: behavior.pulsar.sojevent.deadletter
    dist:
      topic-config:
        - ""

kafka:
  consumer:
    stream: behavior.totalv3
    group-id: sojourner-distributor-pre-prod-totalv3
    topic:
      - behavior.totalv3.sojevent-nonbot-rno
      - behavior.totalv3.sojevent-nonbot-lvs
    bootstrap-servers:
      rno:
        - rhs-lpdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      lvs:
        - rhs-opdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092

  producer:
    stream: behavior.pulsar
    bootstrap-servers:
      rno:
        - rhs-okrvkiaa-kfk-rno-1.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-2.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-3.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-4.rheos-streaming-prod.svc.25.tess.io:9092
        - rhs-okrvkiaa-kfk-rno-5.rheos-streaming-prod.svc.25.tess.io:9092
      slc:
        - rhs-qisvkiaa-kfk-slc-1.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-qisvkiaa-kfk-slc-2.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-qisvkiaa-kfk-slc-3.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-qisvkiaa-kfk-slc-4.rheos-streaming-prod.svc.45.tess.io:9092
        - rhs-qisvkiaa-kfk-slc-5.rheos-streaming-prod.svc.45.tess.io:9092

rest-client:
  config:
    profile: pre-prod
