flink:
  app:
    name: Sojourner Non-Bot Event Distributor - Prod - LVS
    parallelism:
      source: 200
      sink-kafka: 200
    source:
      dc: lvs
      operator-name: Non-bot SojEvent Source
    sink:
      dc: slc
      operator-name: Non-bot SojEvent Sink
    dist:
      topic-config:
        - "dss-gro:behavior.pulsar.customized.dss-gro"
        - "dss-ads-pvp-hsa:behavior.pulsar.customized.ads-pvp-hsa"
        - "srch-lst:behavior.pulsar.event.lst-srch"
        - "entry-page:behavior.pulsar.sojsession.entrypage"
        - "mt-mobile-mc3ur:behavior.pulsar.customized.mc3ur"
        - "expc-native-events:behavior.pulsar.customized.expc-native-events"
        - "srch-auto-complete:behavior.pulsar.customized.srch-auto-complete"
        - "srpGist:behavior.pulsar.customized.srpGist"

kafka:
  consumer:
    group-id: sojourner-distributor-prod-lvs
    topic:
      - behavior.totalv2.sojevent-nonbot-rno
      - behavior.totalv2.sojevent-nonbot-lvs
