flink:
  app:
    name: Sojourner Non-Bot Session Distributor - Prod - RNO
    parallelism:
      source: 50
      sink-kafka: 50
    source:
      dc: rno
      operator-name: Non-bot SojSession Source
    sink:
      dc: rno
      operator-name: Non-bot SojSession Sink
      kafka:
        topic: behavior.pulsar.sojsession.sessionend

kafka:
  consumer:
    stream: behavior.totalv3
    group-id: sojourner-distributor-prod-rno
    topic:
      - behavior.totalv3.sojsession-nonbot-rno
      - behavior.totalv3.sojsession-nonbot-lvs
    bootstrap-servers:
      rno:
        - rhs-lpdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-lpdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
      lvs:
        - rhs-opdwkiaa-kfk-1.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-2.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-3.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-4.rheos-streaming-prod.vip.ebay.com:9092
        - rhs-opdwkiaa-kfk-5.rheos-streaming-prod.vip.ebay.com:9092
