flink:
  app:
    name: Sojourner Non-Bot Session Distributor - Pre-Prod
    parallelism:
      source: 50
      sink-kafka: 50
    source:
      dc: rno
      operator-name: Non-bot SojSession Source
    sink:
      dc: rno
      operator-name: Non-bot SojSession Sink
      kafka:
        topic: behavior.total.new.sojsession.nonbot.test

kafka:
  consumer:
    stream: behavior.total.new
    group-id: sojourner-distributor-pre-prod-session
    topic:
      - behavior.total.new.sojsession.nonbot
    bootstrap-servers:
      rno:
        - rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092

  producer:
    stream: behavior.total.new
    bootstrap-servers:
      rno:
        - rhs-pbuvkiaa-kfk-rno-1.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-2.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-3.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-4.rheos-streaming-prod.svc.26.tess.io:9092
        - rhs-pbuvkiaa-kfk-rno-5.rheos-streaming-prod.svc.26.tess.io:9092
