flink:
  app:
    name: Sojourner Non-Bot Session Distributor - Prod - RNO
    parallelism:
      source: 50
      sink-kafka: 50
    source:
      dc: rno
      operator-name: Non-bot SojSession Source
    sink:
      dc: rno
      operator-name: Non-bot SojSession Sink
      kafka:
        topic: behavior.pulsar.sojsession.sessionend

kafka:
  consumer:
    stream: behavior.totalv2
    group-id: sojourner-distributor-prod-rno
    topic:
      - behavior.totalv2.sojsession-nonbot-rno
      - behavior.totalv2.sojsession-nonbot-lvs